package main

import "strings"

var localizedLanguageNames = map[string]map[string]string{
	"ru": {
		"ru": "русский",
		"en": "английский",
		"es": "испанский",
		"de": "немецкий",
		"fr": "французский",
		"it": "итальянский",
		"zh": "китайский",
		"ja": "японский",
		"ko": "корейский",
		"tg": "таджикский",
		"uz": "узбекский",
		"tt": "татарский",
		"hy": "армянский",
		"kk": "казахский",
		"ky": "киргизский",
		"ka": "грузинский",
		"uk": "украинский",
		"pl": "польский",
		"ro": "румынский",
		"pt": "португальский",
	},
	"en": {
		"ru": "Russian",
		"en": "English",
		"es": "Spanish",
		"de": "German",
		"fr": "French",
		"it": "Italian",
		"zh": "Chinese",
		"ja": "Japanese",
		"ko": "Korean",
		"tg": "Tajik",
		"uz": "Uzbek",
		"tt": "Tatar",
		"hy": "Armenian",
		"kk": "Kazakh",
		"ky": "Kyrgyz",
		"ka": "Georgian",
		"uk": "Ukrainian",
		"pl": "Polish",
		"ro": "Romanian",
		"pt": "Portuguese",
	},
	"es": {
		"ru": "ruso",
		"en": "inglés",
		"es": "español",
		"de": "alemán",
		"fr": "francés",
		"it": "italiano",
		"zh": "chino",
		"ja": "japonés",
		"ko": "coreano",
		"tg": "tayiko",
		"uz": "uzbeko",
		"tt": "tártaro",
		"hy": "armenio",
		"kk": "kazajo",
		"ky": "kirguís",
		"ka": "georgiano",
		"uk": "ucraniano",
		"pl": "polaco",
		"ro": "rumano",
		"pt": "portugués",
	},
	"de": {
		"ru": "Russisch",
		"en": "Englisch",
		"es": "Spanisch",
		"de": "Deutsch",
		"fr": "Französisch",
		"it": "Italienisch",
		"zh": "Chinesisch",
		"ja": "Japanisch",
		"ko": "Koreanisch",
		"tg": "Tadschikisch",
		"uz": "Usbekisch",
		"tt": "Tatarisch",
		"hy": "Armenisch",
		"kk": "Kasachisch",
		"ky": "Kirgisisch",
		"ka": "Georgisch",
		"uk": "Ukrainisch",
		"pl": "Polnisch",
		"ro": "Rumänisch",
		"pt": "Portugiesisch",
	},
	"fr": {
		"ru": "russe",
		"en": "anglais",
		"es": "espagnol",
		"de": "allemand",
		"fr": "français",
		"it": "italien",
		"zh": "chinois",
		"ja": "japonais",
		"ko": "coréen",
		"tg": "tadjik",
		"uz": "ouzbek",
		"tt": "tatar",
		"hy": "arménien",
		"kk": "kazakh",
		"ky": "kirghize",
		"ka": "géorgien",
		"uk": "ukrainien",
		"pl": "polonais",
		"ro": "roumain",
		"pt": "portugais",
	},
	"it": {
		"ru": "russo",
		"en": "inglese",
		"es": "spagnolo",
		"de": "tedesco",
		"fr": "francese",
		"it": "italiano",
		"zh": "cinese",
		"ja": "giapponese",
		"ko": "coreano",
		"tg": "tagico",
		"uz": "uzbeco",
		"tt": "tataro",
		"hy": "armeno",
		"kk": "kazako",
		"ky": "kirghiso",
		"ka": "georgiano",
		"uk": "ucraino",
		"pl": "polacco",
		"ro": "rumeno",
		"pt": "portoghese",
	},
	"zh": {
		"ru": "俄语",
		"en": "英语",
		"es": "西班牙语",
		"de": "德语",
		"fr": "法语",
		"it": "意大利语",
		"zh": "中文",
		"ja": "日语",
		"ko": "韩语",
		"tg": "塔吉克语",
		"uz": "乌兹别克语",
		"tt": "鞑靼语",
		"hy": "亚美尼亚语",
		"kk": "哈萨克语",
		"ky": "吉尔吉斯语",
		"ka": "格鲁吉亚语",
		"uk": "乌克兰语",
		"pl": "波兰语",
		"ro": "罗马尼亚语",
		"pt": "葡萄牙语",
	},
	"ja": {
		"ru": "ロシア語",
		"en": "英語",
		"es": "スペイン語",
		"de": "ドイツ語",
		"fr": "フランス語",
		"it": "イタリア語",
		"zh": "中国語",
		"ja": "日本語",
		"ko": "韓国語",
		"tg": "タジク語",
		"uz": "ウズベク語",
		"tt": "タタール語",
		"hy": "アルメニア語",
		"kk": "カザフ語",
		"ky": "キルギス語",
		"ka": "ジョージア語",
		"uk": "ウクライナ語",
		"pl": "ポーランド語",
		"ro": "ルーマニア語",
		"pt": "ポルトガル語",
	},
	"ko": {
		"ru": "러시아어",
		"en": "영어",
		"es": "스페인어",
		"de": "독일어",
		"fr": "프랑스어",
		"it": "이탈리아어",
		"zh": "중국어",
		"ja": "일본어",
		"ko": "한국어",
		"tg": "타지크어",
		"uz": "우즈베크어",
		"tt": "타타르어",
		"hy": "아르메니아어",
		"kk": "카자흐어",
		"ky": "키르기스어",
		"ka": "조지아어",
		"uk": "우크라이나어",
		"pl": "폴란드어",
		"ro": "루마니아어",
		"pt": "포르투갈어",
	},
	"tg": {
		"ru": "русӣ",
		"en": "англисӣ",
		"es": "испанӣ",
		"de": "немисӣ",
		"fr": "франсузӣ",
		"it": "италиявӣ",
		"zh": "хитоӣ",
		"ja": "японӣ",
		"ko": "кореягӣ",
		"tg": "тоҷикӣ",
		"uz": "ӯзбекӣ",
		"tt": "тоторӣ",
		"hy": "арманӣ",
		"kk": "қазоқӣ",
		"ky": "қирғизӣ",
		"ka": "гурҷӣ",
		"uk": "украинӣ",
		"pl": "лаҳистонӣ",
		"ro": "руминӣ",
		"pt": "португалӣ",
	},
	"uz": {
		"ru": "ruscha",
		"en": "inglizcha",
		"es": "ispancha",
		"de": "nemischa",
		"fr": "fransuzcha",
		"it": "italyan",
		"zh": "xitoy",
		"ja": "yapon",
		"ko": "koreyscha",
		"tg": "tojik",
		"uz": "o‘zbek",
		"tt": "tatar",
		"hy": "arman",
		"kk": "qozoqcha",
		"ky": "qirgʻizcha",
		"ka": "gruzincha",
		"uk": "ukrain",
		"pl": "polyakcha",
		"ro": "rumincha",
		"pt": "portugalcha",
	},
	"tt": {
		"ru": "рус",
		"en": "инглиз",
		"es": "испан",
		"de": "алман",
		"fr": "француз",
		"it": "итальян",
		"zh": "кытайча",
		"ja": "япон",
		"ko": "корея",
		"tg": "таҗик",
		"uz": "үзбәк",
		"tt": "татар",
		"hy": "әрмән",
		"kk": "казакъ",
		"ky": "кыргыз",
		"ka": "грузин",
		"uk": "украин",
		"pl": "поляк",
		"ro": "румын",
		"pt": "португал",
	},
	"hy": {
		"ru": "ռուսերեն",
		"en": "անգլերեն",
		"es": "իսպաներեն",
		"de": "գերմաներեն",
		"fr": "ֆրանսերեն",
		"it": "իտալերեն",
		"zh": "չինարեն",
		"ja": "ճապոներեն",
		"ko": "կորեերեն",
		"tg": "տաջիկերեն",
		"uz": "ուզբեկերեն",
		"tt": "թաթարերեն",
		"hy": "հայերեն",
		"kk": "ղազախերեն",
		"ky": "ղրղզերեն",
		"ka": "վրացերեն",
		"uk": "ուկրաիներեն",
		"pl": "լեհերեն",
		"ro": "ռումիներեն",
		"pt": "պորտուգալերեն",
	},
	"kk": {
		"ru": "орыс тілі",
		"en": "ағылшын тілі",
		"es": "испан тілі",
		"de": "неміс тілі",
		"fr": "француз тілі",
		"it": "итальян тілі",
		"zh": "қытай тілі",
		"ja": "жапон тілі",
		"ko": "корей тілі",
		"tg": "тәжік тілі",
		"uz": "өзбек тілі",
		"tt": "татар тілі",
		"hy": "армян тілі",
		"kk": "қазақ тілі",
		"ky": "қырғыз тілі",
		"ka": "грузин тілі",
		"uk": "украин тілі",
		"pl": "поляк тілі",
		"ro": "румын тілі",
		"pt": "португал тілі",
	},
	"ky": {
		"ru": "орусча",
		"en": "англисче",
		"es": "испанча",
		"de": "немисче",
		"fr": "французча",
		"it": "италиянча",
		"zh": "кытайча",
		"ja": "жапончо",
		"ko": "корейче",
		"tg": "тажикче",
		"uz": "өзбекче",
		"tt": "татарча",
		"hy": "армянча",
		"kk": "казакча",
		"ky": "кыргызча",
		"ka": "грузинче",
		"uk": "украинче",
		"pl": "полякча",
		"ro": "румынча",
		"pt": "португалча",
	},
	"ka": {
		"ru": "რუსული",
		"en": "ინგლისური",
		"es": "ესპანური",
		"de": "გერმანული",
		"fr": "ფრანგული",
		"it": "იტალიური",
		"zh": "ჩინური",
		"ja": "იაპონური",
		"ko": "კორეული",
		"tg": "ტაჯიკური",
		"uz": "უზბეკური",
		"tt": "თათრული",
		"hy": "სომხური",
		"kk": "ყაზახური",
		"ky": "ყირგიზული",
		"ka": "ქართული",
		"uk": "უკრაინული",
		"pl": "პოლონური",
		"ro": "რუმინული",
		"pt": "პორტუგალიური",
	},
	"uk": {
		"ru": "російська",
		"en": "англійська",
		"es": "іспанська",
		"de": "німецька",
		"fr": "французька",
		"it": "італійська",
		"zh": "китайська",
		"ja": "японська",
		"ko": "корейська",
		"tg": "таджицька",
		"uz": "узбецька",
		"tt": "татарська",
		"hy": "вірменська",
		"kk": "казахська",
		"ky": "киргизька",
		"ka": "грузинська",
		"uk": "українська",
		"pl": "польська",
		"ro": "румунська",
		"pt": "португальська",
	},
	"pl": {
		"ru": "rosyjski",
		"en": "angielski",
		"es": "hiszpański",
		"de": "niemiecki",
		"fr": "francuski",
		"it": "włoski",
		"zh": "chiński",
		"ja": "japoński",
		"ko": "koreański",
		"tg": "tadżycki",
		"uz": "uzbecki",
		"tt": "tatarski",
		"hy": "ormiański",
		"kk": "kazachski",
		"ky": "kirgiski",
		"ka": "gruziński",
		"uk": "ukraiński",
		"pl": "polski",
		"ro": "rumuński",
		"pt": "portugalski",
	},
	"ro": {
		"ru": "rusă",
		"en": "engleză",
		"es": "spaniolă",
		"de": "germană",
		"fr": "franceză",
		"it": "italiană",
		"zh": "chineză",
		"ja": "japoneză",
		"ko": "coreeană",
		"tg": "tadjică",
		"uz": "uzbecă",
		"tt": "tătară",
		"hy": "armeană",
		"kk": "kazahă",
		"ky": "kârgâză",
		"ka": "georgiană",
		"uk": "ucraineană",
		"pl": "poloneză",
		"ro": "română",
		"pt": "portugheză",
	},
	"pt": {
		"ru": "russo",
		"en": "inglês",
		"es": "espanhol",
		"de": "alemão",
		"fr": "francês",
		"it": "italiano",
		"zh": "chinês",
		"ja": "japonês",
		"ko": "coreano",
		"tg": "tadjique",
		"uz": "uzbeque",
		"tt": "tártaro",
		"hy": "armênio",
		"kk": "cazaque",
		"ky": "quirguiz",
		"ka": "georgiano",
		"uk": "ucraniano",
		"pl": "polonês",
		"ro": "romeno",
		"pt": "português",
	},
}

func localizedLanguageNameForInterface(language learningLanguage, interfaceCode string) string {
	interfaceCode = normalizeInterfaceLanguage(interfaceCode)
	if names, ok := localizedLanguageNames[interfaceCode]; ok {
		if name := strings.TrimSpace(names[language.Code]); name != "" {
			return name
		}
	}
	if interfaceCode == "ru" && strings.TrimSpace(language.Name) != "" {
		return language.Name
	}
	return language.NativeName
}

func languageButtonLabel(language learningLanguage, interfaceCode string) string {
	native := strings.TrimSpace(language.InterfaceName)
	if native == "" {
		native = strings.TrimSpace(language.NativeName)
	}
	localized := strings.TrimSpace(localizedLanguageNameForInterface(language, interfaceCode))
	if localized == "" || strings.EqualFold(native, localized) {
		return native
	}
	return native + " (" + localized + ")"
}

func translatorLanguageDisplayName(code string, user userState) string {
	code = normalizeTranslatorSource(code)
	if code == translationAutoCode {
		return ui(user).Tool.AutoDetect
	}
	return languageButtonLabel(learningLanguageByCode(code), user.InterfaceLanguage)
}
