package main

func init() {
	levelAssessmentQuestionsByLanguage["zh"] = professionalAssessmentQuestions(chineseLevelAssessmentQuestions)
	levelAssessmentQuestionsByLanguage["ja"] = professionalAssessmentQuestions(japaneseLevelAssessmentQuestions)
	levelAssessmentQuestionsByLanguage["ko"] = professionalAssessmentQuestions(koreanLevelAssessmentQuestions)
}

var chineseLevelAssessmentQuestions = []levelQuestion{
	{Question: "Choose the natural Chinese greeting:", Options: []string{"你好。", "你是好。", "好你。", "你们好是。"}, CorrectIndex: 0, Points: 4},
	{Question: "Fill the gap: 我 ___ 学生。", Options: []string{"是", "有", "在", "去"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct word for 'water':", Options: []string{"水", "书", "车", "钱"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct negative sentence:", Options: []string{"我不喝咖啡。", "我没喝咖啡每天。", "我喝不咖啡。", "不我喝咖啡。"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct question:", Options: []string{"你叫什么名字？", "你名字什么叫？", "什么你叫名字？", "你叫名字吗什么？"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct measure word:", Options: []string{"一本书", "一只书", "一杯书", "一辆书"}, CorrectIndex: 0, Points: 4},
	{Question: "Fill the gap: 我昨天 ___ 北京。", Options: []string{"去了", "去", "去过着", "会去昨天"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the natural sentence with zai:", Options: []string{"他在家学习。", "他学习在家。", "他在学习家。", "在他家学习。"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct comparison:", Options: []string{"今天比昨天冷。", "今天比昨天很冷。", "今天冷比昨天。", "今天比昨天冷得多吗的。"}, CorrectIndex: 0, Points: 5},
	{Question: "What does 因为 mean?", Options: []string{"because", "although", "therefore", "unless"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct le-aspect sentence:", Options: []string{"我看完了这本书。", "我看了完这本书。", "我完看这本书了。", "我看这本书完。"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the natural time order:", Options: []string{"我明天上午九点去学校。", "我去学校明天九点上午。", "明天我去上午九点学校。", "上午九点学校我明天去。"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct ba-construction:", Options: []string{"请把门关上。", "请门把关上。", "请关上把门。", "请把关上门。"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the correct bei-construction:", Options: []string{"我的手机被他拿走了。", "我的手机把他拿走了。", "他被我的手机拿走了。", "我的手机被拿走他了。"}, CorrectIndex: 0, Points: 7},
	{Question: "Fill the gap: 虽然很累，___ 他还是继续工作。", Options: []string{"但是", "因为", "所以", "如果"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the natural result complement:", Options: []string{"我听懂了。", "我听会了懂。", "我懂听了。", "我听得懂了会。"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the correct potential complement:", Options: []string{"这个字我看不清楚。", "这个字我不看清楚得。", "我看清楚不这个字。", "这个字看我不清楚。"}, CorrectIndex: 0, Points: 7},
	{Question: "What does 尽管 mean?", Options: []string{"although", "immediately", "instead", "because"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the formal connector meaning 'therefore':", Options: []string{"因此", "然后", "还是", "可是"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the correct 把 sentence with result:", Options: []string{"他把问题解释清楚了。", "他把问题清楚解释。", "问题把他解释清楚了。", "他解释把问题清楚了。"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the natural concessive sentence:", Options: []string{"即使下雨，我们也会去。", "即使下雨，我们会也去。", "下雨即使，我们也去会。", "即使我们也下雨会去。"}, CorrectIndex: 0, Points: 9},
	{Question: "Fill the gap: 这个方案值得进一步 ___。", Options: []string{"讨论", "说话", "聊天", "走路"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the precise academic phrase:", Options: []string{"数据表明二者存在相关性。", "数据说两个东西有点关系。", "数据让关系出来。", "两个关系被数据做了。"}, CorrectIndex: 0, Points: 9},
	{Question: "What does 取决于 mean?", Options: []string{"depend on", "give up", "translate into", "look for"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the correct formal passive:", Options: []string{"该决定已被正式批准。", "该决定被正式批准了已经。", "已被该决定正式批准。", "该决定把正式批准。"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the best written-style sentence:", Options: []string{"鉴于证据不足，结论仍需谨慎。", "因为证据少，所以结论小心一点吧。", "证据不够让结论很谨慎做。", "结论由于证据不足小心了。"}, CorrectIndex: 0, Points: 11},
	{Question: "What does 与其...不如... express?", Options: []string{"preference between alternatives", "completed action", "location", "direct object"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the natural pattern:", Options: []string{"与其抱怨，不如行动。", "与其抱怨，不如了行动。", "抱怨与其，行动不如。", "与其行动，不如抱怨更行动。"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the precise rewrite:", Options: []string{"该问题有待进一步研究。", "这个问题等着研究更多。", "问题要被研究等一下。", "研究进一步有问题待。"}, CorrectIndex: 0, Points: 11},
	{Question: "What does 不可避免 mean?", Options: []string{"inevitable", "optional", "temporary", "unclear"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the most formal register:", Options: []string{"该措施的有效性仍有待验证。", "这个办法好不好还得看看。", "措施有效性还没怎么弄。", "办法是不是好以后说。"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the correct complex sentence:", Options: []string{"无论结果如何，我们都应保持客观。", "无论结果如何，我们应都保持客观。", "结果无论如何都我们保持客观。", "无论我们结果如何客观保持。"}, CorrectIndex: 0, Points: 13},
	{Question: "What does 从某种意义上说 mean?", Options: []string{"in a certain sense", "as soon as possible", "for no reason", "on the contrary"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the nuanced academic sentence:", Options: []string{"这一解释虽有启发性，但仍存在局限。", "这个解释很好但是也不好。", "解释有启发可是局限存在得很。", "虽然解释启发，局限还是。"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the formal equivalent of 'question the assumption':", Options: []string{"质疑这一假设", "问这个假设", "把假设问出来", "假设被问题"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the most precise conclusion:", Options: []string{"现有数据尚不足以支持该结论。", "数据现在不够所以结论没法很好。", "结论支持数据不够现在。", "数据让结论支持不了的。"}, CorrectIndex: 0, Points: 13},
}

var japaneseLevelAssessmentQuestions = []levelQuestion{
	{Question: "Choose the natural Japanese greeting:", Options: []string{"こんにちは。", "私はこんにちはです。", "こんにちはをします。", "こんにちはが行く。"}, CorrectIndex: 0, Points: 4},
	{Question: "Fill the gap: 私は学生 ___。", Options: []string{"です", "ます", "を", "で"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct particle: 水 ___ 飲みます。", Options: []string{"を", "が", "に", "へ"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct negative:", Options: []string{"コーヒーを飲みません。", "コーヒーを飲みますない。", "コーヒーない飲みます。", "飲みませんコーヒーを。"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct question:", Options: []string{"お名前は何ですか。", "何ですかお名前は。", "お名前を何です。", "何お名前ですかは。"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct past form:", Options: []string{"昨日、学校へ行きました。", "昨日、学校へ行きますでした。", "昨日、学校へ行くました。", "昨日、学校へ行ったます。"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct te-form request:", Options: []string{"ドアを閉めてください。", "ドアを閉めるください。", "ドアを閉めますください。", "ドアを閉めたください。"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the natural location sentence:", Options: []string{"家で勉強します。", "家に勉強します。", "家を勉強します。", "家が勉強します。"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct comparison:", Options: []string{"今日は昨日より寒いです。", "今日は昨日よりと寒いです。", "今日は昨日から寒いです。", "今日は昨日に寒いです。"}, CorrectIndex: 0, Points: 5},
	{Question: "What does だから mean?", Options: []string{"therefore", "although", "unless", "instead"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct potential form:", Options: []string{"日本語が読めます。", "日本語が読みできます。", "日本語を読まれますできる。", "日本語が読むできます。"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the natural time order:", Options: []string{"明日の朝九時に学校へ行きます。", "九時に学校へ明日の朝行きます。", "学校へ明日九時朝に行きます。", "朝に明日学校九時へ行きます。"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct plain past:", Options: []string{"本を読んだ。", "本を読むた。", "本を読みだ。", "本を読んでたです。"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the correct relative clause:", Options: []string{"昨日会った人", "昨日人に会ったの人", "人昨日会った", "会った昨日の人に"}, CorrectIndex: 0, Points: 7},
	{Question: "Fill the gap: 疲れている ___、勉強を続けた。", Options: []string{"のに", "から", "まで", "だけ"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the correct passive:", Options: []string{"財布を盗まれました。", "財布を盗みられました。", "財布が盗ませました。", "財布を盗んでられました。"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the natural giving expression:", Options: []string{"友達に本をあげました。", "友達を本にあげました。", "本が友達にあげました。", "友達で本をあげました。"}, CorrectIndex: 0, Points: 7},
	{Question: "What does しかし mean?", Options: []string{"however", "because", "already", "only"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the correct causative:", Options: []string{"先生は学生に発表させた。", "先生は学生を発表できた。", "先生は学生に発表したせた。", "先生は学生が発表させた。"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the natural humble form:", Options: []string{"明日伺います。", "明日いらっしゃいます。", "明日参られます。", "明日来ておりますです。"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the correct conditional:", Options: []string{"時間があれば、行きます。", "時間があるならば、行きますた。", "時間があれば、行くでした。", "時間なら、行きれば。"}, CorrectIndex: 0, Points: 9},
	{Question: "What does にもかかわらず mean?", Options: []string{"despite", "because of", "before", "instead of"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the precise written phrase:", Options: []string{"さらなる検討が必要です。", "もっと見ることがいります。", "検討をもっとする必要っぽい。", "必要が検討さらにです。"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the natural result expression:", Options: []string{"問題が明らかになった。", "問題を明らかにしたになった。", "問題が明らかをなった。", "問題になった明らか。"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the correct formal passive:", Options: []string{"その決定は正式に承認された。", "その決定は正式に承認したされた。", "正式にその決定を承認された。", "その決定が承認させた。"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the best written-style sentence:", Options: []string{"証拠が不十分であるため、結論には慎重さが求められる。", "証拠が少ないから結論は気をつける感じです。", "結論が慎重を求めて証拠少ない。", "証拠不足で結論を注意する。"}, CorrectIndex: 0, Points: 11},
	{Question: "What does 一方で mean?", Options: []string{"on the other hand", "immediately", "by accident", "at home"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the natural pattern:", Options: []string{"努力すればするほど上達する。", "努力すればほどする上達する。", "努力ほどすれば上達する。", "上達すればするほど努力。"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the precise rewrite:", Options: []string{"この点については再検討の余地がある。", "この点はもう一回見る場所がある。", "再検討がこの点に余地する。", "この点について余地を再検討ある。"}, CorrectIndex: 0, Points: 11},
	{Question: "What does 避けられない mean?", Options: []string{"unavoidable", "unclear", "temporary", "optional"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the most formal register:", Options: []string{"本施策の有効性はなお検証を要する。", "このやり方が効くかまだ見ます。", "施策の効き目は検証したい感じです。", "有効性がまだ要ります検証。"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the correct complex sentence:", Options: []string{"結果がどうであれ、客観性を保つべきだ。", "結果どうであれ、客観性を保つべきでしたます。", "どう結果であれ客観性保つべき。", "結果が客観性をどう保つであれ。"}, CorrectIndex: 0, Points: 13},
	{Question: "What does ある意味では mean?", Options: []string{"in a certain sense", "for no reason", "as soon as possible", "on the contrary"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the nuanced academic sentence:", Options: []string{"この説明は示唆に富むが、限界も残る。", "この説明はいいけど悪いところもある。", "説明が示唆に富んで限界を残る。", "限界も残るが説明は富む。"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the formal equivalent of 'question the assumption':", Options: []string{"その仮定に疑問を呈する", "仮定を質問する", "仮定に聞く", "質問で仮定をする"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the most precise conclusion:", Options: []string{"現時点のデータだけではその結論を支持できない。", "今のデータだけだと結論はまあ無理です。", "データが結論を支持できないだけ今。", "結論はデータだけで支持しません現時点。"}, CorrectIndex: 0, Points: 13},
}

var koreanLevelAssessmentQuestions = []levelQuestion{
	{Question: "Choose the natural Korean greeting:", Options: []string{"안녕하세요.", "저는 안녕하세요입니다.", "안녕하세요를 합니다.", "안녕하세요가 갑니다."}, CorrectIndex: 0, Points: 4},
	{Question: "Fill the gap: 저는 학생 ___", Options: []string{"입니다.", "있습니다.", "합니다.", "갑니다."}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct object particle:", Options: []string{"물을 마십니다.", "물이 마십니다.", "물에 마십니다.", "물로 마십니다."}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct negative:", Options: []string{"커피를 마시지 않습니다.", "커피를 마십니다 안.", "커피가 안을 마십니다.", "안 커피를 마십니다지."}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct question:", Options: []string{"이름이 뭐예요?", "뭐 이름이에요가?", "이름을 뭐예요?", "뭐예요 이름이요?"}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct past form:", Options: []string{"어제 학교에 갔어요.", "어제 학교에 가요었어요.", "어제 학교에 갑니다했어요.", "어제 학교가 갔어요에."}, CorrectIndex: 0, Points: 4},
	{Question: "Choose the correct request:", Options: []string{"문을 닫아 주세요.", "문을 닫다 주세요.", "문이 닫아 주세요.", "문을 닫습니다 주세요."}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the natural location sentence:", Options: []string{"집에서 공부해요.", "집에 공부해요.", "집을 공부해요.", "집이 공부해요."}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct comparison:", Options: []string{"오늘은 어제보다 추워요.", "오늘은 어제보다를 추워요.", "오늘은 어제에게 추워요.", "오늘은 추워요보다 어제."}, CorrectIndex: 0, Points: 5},
	{Question: "What does 그래서 mean?", Options: []string{"therefore", "although", "unless", "instead"}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct ability expression:", Options: []string{"한국어를 읽을 수 있어요.", "한국어를 읽기 수 있어요.", "한국어가 읽을 있어요 수.", "한국어를 읽어요 수 있습니다."}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the natural time order:", Options: []string{"내일 아침 아홉 시에 학교에 가요.", "학교에 내일 아홉 시 아침에 가요.", "아홉 시 학교 내일 아침에 가요.", "내일 학교 아침에 아홉 시를 가요."}, CorrectIndex: 0, Points: 5},
	{Question: "Choose the correct connective:", Options: []string{"책을 읽고 잤어요.", "책을 읽어서 잤어요를.", "책이 읽고 잤어요.", "읽고 책을 잠었어요."}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the correct relative clause:", Options: []string{"어제 만난 사람", "어제 사람을 만난의", "사람 어제 만난", "만난 어제에 사람을"}, CorrectIndex: 0, Points: 7},
	{Question: "Fill the gap: 피곤했지만 ___ 계속 공부했어요.", Options: []string{"그래도", "그래서", "왜냐하면", "까지"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the correct passive:", Options: []string{"문이 닫혔어요.", "문이 닫았어요.", "문을 닫혔어요.", "문이 닫게 했어요."}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the natural honorific:", Options: []string{"선생님께서 오셨어요.", "선생님이 왔어 낮춤.", "선생님께서 왔어요 했다.", "선생님을 오셨어요."}, CorrectIndex: 0, Points: 7},
	{Question: "What does 하지만 mean?", Options: []string{"however", "because", "already", "only"}, CorrectIndex: 0, Points: 7},
	{Question: "Choose the correct causative:", Options: []string{"선생님이 학생에게 발표하게 했어요.", "선생님이 학생을 발표했어요 시켰다.", "학생에게 선생님이 발표했어요.", "발표가 학생에게 하게 했어요."}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the natural humble expression:", Options: []string{"내일 찾아뵙겠습니다.", "내일 오시겠습니다 제가.", "내일 가시겠습니다.", "내일 봐요 낮춤겠습니다."}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the correct conditional:", Options: []string{"시간이 있으면 갈게요.", "시간이 있으면 갔어요 내일.", "시간 있으면을 갈게요.", "갈게요 시간이면 있으면."}, CorrectIndex: 0, Points: 9},
	{Question: "What does 그럼에도 불구하고 mean?", Options: []string{"despite that", "because of that", "before that", "instead of that"}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the precise written phrase:", Options: []string{"추가 검토가 필요합니다.", "더 봐야 하는 느낌입니다.", "검토를 더 필요해요 합니다.", "필요가 검토를 추가합니다."}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the natural result expression:", Options: []string{"문제가 분명해졌습니다.", "문제를 분명하게 되었습니다가.", "문제가 분명했습니다 되다.", "분명해 문제를 졌습니다."}, CorrectIndex: 0, Points: 9},
	{Question: "Choose the correct formal passive:", Options: []string{"그 결정은 공식적으로 승인되었습니다.", "그 결정은 공식적으로 승인했습니다 되었습니다.", "공식적으로 그 결정을 승인되었습니다.", "그 결정이 승인시켰습니다."}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the best written-style sentence:", Options: []string{"증거가 불충분하므로 결론에는 신중함이 요구됩니다.", "증거가 적어서 결론은 조심해야 하는 것 같아요.", "결론이 신중함을 요구해서 증거가 적습니다.", "증거 부족으로 결론을 조심합니다."}, CorrectIndex: 0, Points: 11},
	{Question: "What does 반면에 mean?", Options: []string{"on the other hand", "immediately", "by accident", "at home"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the natural pattern:", Options: []string{"연습하면 할수록 실력이 늘어요.", "연습하면 할수록을 실력이 늘어요.", "실력이 늘수록 연습하면 해요.", "연습할수록 하면 실력 늘어요."}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the precise rewrite:", Options: []string{"이 점은 재검토의 여지가 있습니다.", "이 점은 다시 볼 자리 있어요.", "재검토가 이 점에 여지를 합니다.", "이 점에 여지가 재검토 있습니다."}, CorrectIndex: 0, Points: 11},
	{Question: "What does 불가피하다 mean?", Options: []string{"unavoidable", "unclear", "temporary", "optional"}, CorrectIndex: 0, Points: 11},
	{Question: "Choose the most formal register:", Options: []string{"본 조치의 효과성은 아직 검증이 필요합니다.", "이 방법이 되는지는 아직 봐야 해요.", "조치 효과는 검증 느낌이 필요합니다.", "효과성이 아직 필요합니다 검증."}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the correct complex sentence:", Options: []string{"결과가 어떻든 객관성을 유지해야 합니다.", "결과가 어떻든을 객관성 유지해야 합니다.", "어떻든 결과 객관성을 해야 유지.", "결과가 객관성을 어떻게 유지하든."}, CorrectIndex: 0, Points: 13},
	{Question: "What does 어떤 의미에서는 mean?", Options: []string{"in a certain sense", "for no reason", "as soon as possible", "on the contrary"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the nuanced academic sentence:", Options: []string{"이 설명은 시사점이 크지만 한계도 남아 있습니다.", "이 설명은 좋지만 나쁜 점도 있어요.", "설명이 시사점이 커서 한계를 남아 있습니다.", "한계도 남지만 설명은 큽니다."}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the formal equivalent of 'question the assumption':", Options: []string{"그 가정에 의문을 제기하다", "가정을 질문하다", "가정에게 묻다", "질문으로 가정을 하다"}, CorrectIndex: 0, Points: 13},
	{Question: "Choose the most precise conclusion:", Options: []string{"현재 자료만으로는 그 결론을 뒷받침하기 어렵습니다.", "지금 자료만으로 결론은 좀 어려워요.", "자료가 결론을 어렵게 뒷받침 현재.", "결론은 자료만으로 뒷받침하지 않습니다 현재."}, CorrectIndex: 0, Points: 13},
}
