package main

func init() {
	extraAssessments := map[string][]levelQuestion{
		"pt": professionalAssessmentQuestions(portugueseLevelAssessmentQuestions),
		"ru": professionalAssessmentQuestions(russianLevelAssessmentQuestions),
		"pl": professionalAssessmentQuestions(polishLevelAssessmentQuestions),
		"ro": professionalAssessmentQuestions(romanianLevelAssessmentQuestions),
		"uk": professionalAssessmentQuestions(ukrainianLevelAssessmentQuestions),
		"kk": professionalAssessmentQuestions(kazakhLevelAssessmentQuestions),
		"ky": professionalAssessmentQuestions(kyrgyzLevelAssessmentQuestions),
		"uz": professionalAssessmentQuestions(uzbekLevelAssessmentQuestions),
		"tg": professionalAssessmentQuestions(tajikLevelAssessmentQuestions),
		"tt": professionalAssessmentQuestions(tatarLevelAssessmentQuestions),
		"hy": professionalAssessmentQuestions(armenianLevelAssessmentQuestions),
		"ka": professionalAssessmentQuestions(georgianLevelAssessmentQuestions),
	}
	for language, questions := range extraAssessments {
		levelAssessmentQuestionsByLanguage[language] = questions
	}
}

func professionalAssessmentQuestions(questions []levelQuestion) []levelQuestion {
	result := make([]levelQuestion, len(questions))
	for index, question := range questions {
		result[index] = question
		if len(question.Options) != 4 || question.CorrectIndex != 0 {
			continue
		}
		shift := index % len(question.Options)
		options := append([]string{}, question.Options[shift:]...)
		options = append(options, question.Options[:shift]...)
		result[index].Options = options
		result[index].CorrectIndex = (len(question.Options) - shift) % len(question.Options)
	}
	return result
}

var russianLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: Я ___", Options: []string{"студент", "студента", "студентом", "студенты"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Это ___ книга.", Options: []string{"интересная", "интересный", "интересное", "интересные"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: У меня ___ брат.", Options: []string{"есть", "это", "быть", "имеет"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Я живу ___ Москве.", Options: []string{"в", "на", "к", "из"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: стол - ___", Options: []string{"столы", "стола", "столами", "столовой"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Мне двадцать лет.", "Я двадцать лет имею.", "Я двадцать лет есть.", "Мне двадцать годы."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Вчера я ___ дома.", Options: []string{"был", "буду", "быть", "есть вчера"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный падеж:", Options: []string{"Я вижу новую книгу.", "Я вижу новая книга.", "Я вижу новой книге.", "Я вижу новую книге."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Каждый день я ___ новости.", Options: []string{"читаю", "прочитал", "прочитаю", "читать"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный вариант движения:", Options: []string{"Я иду в университет.", "Я еду пешком в университет.", "Я хожу сейчас в университет.", "Я иду университетом."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: У меня нет ___", Options: []string{"времени", "время", "временем", "времена"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери comparative:", Options: []string{"Этот текст понятнее, чем тот.", "Этот текст более понятнее тот.", "Этот текст понятный чем тот.", "Этот текст самый понятнее."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Если будет время, я тебе ___", Options: []string{"позвоню", "позвонил вчера", "звонить буду вчера", "звонил бы завтра"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери relative construction:", Options: []string{"Человек, которого я видел вчера, живёт здесь.", "Человек которого я видел вчера живёт здесь без запятой.", "Человек я видел вчера живёт здесь.", "Вчера видел человек живёт здесь."}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит тем не менее?", Options: []string{"однако / несмотря на это", "поэтому", "никогда", "вместо этого"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильный вид:", Options: []string{"Я уже прочитал книгу.", "Я уже читал книгу до конца.", "Я уже буду читать книгу вчера.", "Я уже читаю книгу завтра."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Он сказал, что позже ___", Options: []string{"придёт", "пришёл завтра", "прийти", "приходил завтра вчера"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Это зависит от ситуации.", "Это зависит ситуацию.", "Это зависит с ситуацией.", "Это зависит на ситуацию."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери conditional:", Options: []string{"Если бы я знал, я бы сказал раньше.", "Если я знал бы, я сказал раньше бы.", "Если бы я знаю, я скажу вчера.", "Знал если, сказал бы раньше."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Несмотря на усталость, он работу ___", Options: []string{"продолжил", "продолжать завтра", "продолжает вчера", "продолженный был"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит учитывать?", Options: []string{"принимать во внимание", "вести счёт руками", "платить", "забывать"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери formal variant:", Options: []string{"Эта мера оказалась частично эффективной.", "Эта мера была немного хорошей.", "Мера сделала эффективность.", "Мера как-то работает."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Чем больше практикуешься, ___ говоришь.", Options: []string{"тем лучше", "тем более хорошо", "лучше много", "много тем хорошо"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери деепричастную конструкцию:", Options: []string{"Проанализировав данные, мы изменили гипотезу.", "Проанализировать данные, мы изменили гипотезу.", "Данные проанализированные, мы изменили.", "Данные анализируя были гипотеза."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Достоверность этого вывода вызывает ___", Options: []string{"сомнения", "сомневаться", "сомнительный", "сомневался"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит ставить под сомнение?", Options: []string{"оспаривать / подвергать сомнению", "просто задавать вопрос", "подтверждать", "откладывать"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери academic precise variant:", Options: []string{"Данные указывают на связь, но не доказывают её.", "Данные, возможно, доказывают всё.", "Связь есть, потому что есть данные.", "Данные сами являются связью."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери correct formal phrase:", Options: []string{"Рассматриваемый вопрос является существенным.", "Вопрос рассматривание существенный.", "Рассмотрение вопрос существенный есть.", "Вопрос смотрится существенным."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит вопреки?", Options: []string{"несмотря на / наперекор", "по причине", "до этого", "вместо этого"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"Этот вопрос требует дополнительного анализа.", "Этот вопрос хочет ещё посмотреть.", "Анализ вопрос надо делать.", "Вопрос есть для анализа."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Если новые данные подтвердятся, вывод ___", Options: []string{"будет пересмотрен", "пересмотреть вчера", "пересмотрел завтра", "пересмотренный быть"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери complex concessive construction:", Options: []string{"Какими бы убедительными ни казались аргументы, их необходимо проверить.", "Аргументы убедительные, но проверка была нужна.", "Сколько аргументов есть, проверять нужно.", "Аргументы кажутся убедительно проверка."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит не оправдать ожиданий?", Options: []string{"оказаться ниже ожидаемого уровня", "полностью превзойти", "ждать молча", "начать игру"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери most precise variant:", Options: []string{"На основании имеющихся данных этот вывод представляется преждевременным.", "Данные смотрят, вывод ранний.", "Вывод сейчас говорит данные.", "У вывода нет времени."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит с точки зрения?", Options: []string{"с позиции / в аспекте", "с места стояния", "несмотря на", "сразу после"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери sentence with best nuance:", Options: []string{"Решение представляется перспективным, хотя его реализация сопряжена с трудностями.", "Решение хорошее, но трудное и плохое.", "Решение даёт надежду реализация трудность.", "Решение, может быть, хорошо делать."}, CorrectIndex: 0, Points: 13},
}

var portugueseLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: ___ livro é interessante.", Options: []string{"O", "A", "Os", "As"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Eu ___ português todos os dias.", Options: []string{"estudo", "estuda", "estudar", "estudando"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный вариант: Nós ___ de Lisboa.", Options: []string{"somos", "é", "sou", "estamos"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Tenho vinte anos.", "Sou vinte anos.", "Estou vinte anos.", "Faço vinte anos sempre."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Ela não ___ café.", Options: []string{"bebe", "bebem", "beber", "bebendo"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный plural: a cidade - as ___", Options: []string{"cidades", "cidadas", "cidadees", "cidadãos"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Ontem eu ___ ao cinema.", Options: []string{"fui", "vou", "ia", "irei"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный вариант с estar: A porta ___ aberta.", Options: []string{"está", "é", "são", "estão"}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Gosto ___ música brasileira.", Options: []string{"de", "a", "em", "por"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный comparativo:", Options: []string{"Este texto é mais claro do que aquele.", "Este texto é mais claro que aquele mais.", "Este texto é claro mais do aquele.", "Este texto é maior claro."}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Preciso trabalhar amanhã.", "Preciso de trabalhar amanhã.", "Preciso trabalho amanhã.", "Preciso que trabalhar amanhã."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Se tiver tempo, eu ___ você.", Options: []string{"ajudo", "ajudaria", "ajudei", "ajudava sempre"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный pretérito perfeito:", Options: []string{"Já terminei o relatório.", "Já terminava o relatório hoje.", "Já tenho terminar o relatório.", "Já termino ontem o relatório."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Espero que você ___ cedo.", Options: []string{"chegue", "chega", "chegará", "chegar"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильный pronome:", Options: []string{"Eu o vi ontem.", "Eu vi-o ontem no português brasileiro sempre.", "Eu lhe vi ontem.", "Eu vi ele ontem formalmente."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: A pessoa ___ falei mora aqui.", Options: []string{"com quem", "que", "onde", "cujo"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Embora estivesse cansado, continuei.", "Embora estava cansado, continuei.", "Apesar estava cansado, continuei.", "Embora cansado eu continuei estava."}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит levar em conta?", Options: []string{"considerar", "transportar uma conta", "pagar imediatamente", "esquecer de propósito"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильный futuro do subjuntivo:", Options: []string{"Quando eu chegar, aviso.", "Quando eu chego, aviso amanhã.", "Quando eu chegarei, aviso.", "Quando chegar eu avisaria ontem."}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери правильную voz passiva:", Options: []string{"O documento foi assinado ontem.", "O documento assinou ontem.", "O documento foi assinar ontem.", "O documento é assinado ontem por passado."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Se eu soubesse, ___ antes.", Options: []string{"teria avisado", "avisarei", "tinha avisar", "avisava amanhã"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери наиболее точный вариант:", Options: []string{"A medida mostrou-se parcialmente eficaz.", "A medida foi um pouco boa.", "A medida fez eficácia parcial.", "A medida funciona coisa."}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит pôr em causa?", Options: []string{"questionar", "colocar numa causa judicial", "aprovar", "explicar facilmente"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери правильный discurso indireto:", Options: []string{"Ele disse que viria no dia seguinte.", "Ele disse que virá amanhã ontem.", "Ele disse que vem no dia seguinte passado.", "Ele disse que vinha amanhã futuro."}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери правильный infinitivo pessoal:", Options: []string{"É importante chegarmos cedo.", "É importante chegar nós cedo.", "É importante chegamos cedo.", "É importante que chegarmos cedo."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Por mais que ele ___, não conseguiu convencer todos.", Options: []string{"tentasse", "tentou", "tentará", "tentar"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери формальный связующий элемент:", Options: []string{"No entanto, os dados ainda são insuficientes.", "Daí que os dados ainda insuficientes.", "Mas só que os dados são pouco.", "Então os dados ainda nada."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери правильную конструкцию:", Options: []string{"Tendo analisado os resultados, reformulámos a hipótese.", "Ter analisado os resultados, reformulámos.", "Analisando tido os resultados, reformulámos.", "Tendo analisar resultados, reformulámos."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит não obstante?", Options: []string{"apesar disso", "por causa disso", "em vez disso", "antes disso"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери самый естественный вариант:", Options: []string{"A questão permanece por resolver.", "A questão fica resolver.", "A questão continua sem resolvê-la por si.", "A pergunta está não resolvida fazer."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери наиболее точный академический вариант:", Options: []string{"A evidência aponta para uma correlação, mas não a comprova.", "A evidência prova tudo talvez.", "A evidência não tem nada e prova.", "A correlação faz prova completa."}, CorrectIndex: 0, Points: 13},
	{Question: "Заполни пропуск: Caso se ___ novas informações, a decisão será revista.", Options: []string{"confirmem", "confirma", "confirmará", "confirmar"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери корректную concessiva complexa:", Options: []string{"Ainda que se reconheçam avanços, persistem lacunas relevantes.", "Ainda que reconhecem avanços, lacunas persistem.", "Mesmo reconhecendo que persistem avanços lacunas.", "Ainda reconhecer avanços, persistem lacunas."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит ficar aquém das expectativas?", Options: []string{"não atingir o esperado", "superar totalmente", "esperar em silêncio", "ficar antes no espaço"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери правильный registro formal:", Options: []string{"Cumpre salientar que a amostra é limitada.", "É bom dizer que a amostra é meio pouca.", "Tem que falar que a amostra limita.", "A amostra é pequena, né, portanto."}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери фразу с тонкой модальностью:", Options: []string{"Tal conclusão parece prematura à luz dos dados disponíveis.", "Tal conclusão é falsa porque sim.", "A conclusão está cedo e dados luz.", "Os dados mandam conclusão agora."}, CorrectIndex: 0, Points: 13},
}

var polishLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: To ___ dobry pomysł.", Options: []string{"jest", "są", "być", "mam"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Ona ___ po polsku.", Options: []string{"mówi", "mówią", "mówić", "mówisz"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный падеж: Widzę ___", Options: []string{"nowy dom", "nowego dom", "nowym dom", "nowa dom"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Nie mam ___", Options: []string{"czasu", "czas", "czasem", "czasowi"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: student - ___", Options: []string{"studenci", "studenty", "studentowie zawsze", "studentów są"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Mam dwadzieścia lat.", "Jestem dwadzieścia lat.", "Mam dwadzieścia lata.", "Robię dwadzieścia lat."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Wczoraj ___ w domu.", Options: []string{"byłem", "jestem", "będę", "być"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный aspekt:", Options: []string{"Przeczytałem książkę.", "Czytałem książkę i skończyłem ją całkiem zawsze.", "Przeczytałem książkę przez trzy godziny codziennie.", "Czytać książkę skończyłem."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Interesuję się ___", Options: []string{"muzyką", "muzyka", "muzyki", "muzyce"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный comparativ:", Options: []string{"Ten tekst jest jaśniejszy niż tamten.", "Ten tekst jest bardziej jasny niż tamten zawsze.", "Ten tekst jest jaśniejszy od tamten.", "Ten tekst jest najjaśniejszy niż."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Muszę ___ wcześniej.", Options: []string{"wyjść", "wyjdę", "wyszedłem", "wychodzę że"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Spotkamy się za tydzień.", "Spotkamy się przez tydzień.", "Spotkamy się na tydzień temu.", "Spotkamy tydzień się."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Gdybym miał czas, ___ częściej.", Options: []string{"podróżowałbym", "podróżuję", "podróżowałem jutro", "będę podróżował wczoraj"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильное zdanie względne:", Options: []string{"To jest osoba, którą wczoraj poznałem.", "To jest osoba, która ją poznałem.", "To jest osoba, co poznałem ją.", "To osoba którą poznałem wczoraj ją."}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит mimo to?", Options: []string{"jednak / pomimo tego", "dlatego", "nigdy", "zamiast"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильную форму:", Options: []string{"Chciałbym porozmawiać.", "Chciałbym rozmawiał.", "Chcę bym porozmawiać.", "Chciałem by rozmawiać."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Powiedział, że ___ później.", Options: []string{"przyjdzie", "przyszedł jutro", "przychodziłby wczoraj", "przyjść"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Zależy mi na czasie.", "Zależy mnie czas.", "Zależę na czas.", "Zależy mi czasem."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильный imiesłów:", Options: []string{"Przeczytawszy raport, zmienił zdanie.", "Przeczytając raport wczoraj skończył, zmienił.", "Przeczytać raport, zmienił zdanie.", "Raport przeczytany zmienił zdanie on."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Chociaż ___ późno, kontynuowaliśmy pracę.", Options: []string{"było", "jest", "będzie", "być"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери formalny wariant:", Options: []string{"Należy podkreślić znaczenie tych danych.", "Trzeba powiedzieć, że dane są ważne no.", "Dane robią ważność.", "Powinno się ważność danych."}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит podać coś w wątpliwość?", Options: []string{"zakwestionować", "podać komuś pytanie", "potwierdzić", "opóźnić"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери правильную konstrukcję bezosobową:", Options: []string{"Ustalono nowe zasady.", "Ustalili się nowe zasady.", "Nowe zasady ustalono się.", "Ustalono są zasady."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Im więcej ćwiczysz, ___ mówisz.", Options: []string{"tym lepiej", "tym bardziej dobrze", "więcej dobrze", "lepiej tym więcej"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери правильный tryb przypuszczający:", Options: []string{"Gdyby raport był gotowy, decyzja byłaby łatwiejsza.", "Gdyby raport jest gotowy, decyzja będzie łatwiejsza.", "Jeśli raport byłby gotowy wczoraj, decyzja jest.", "Gdy raport gotowy byłby, decyzja łatwiej."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит pozostawiać wiele do życzenia?", Options: []string{"być niezadowalającym", "być idealnym", "wymagać życzeń", "zostawiać prezent"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери precyzyjny wariant:", Options: []string{"Wyniki wskazują na zależność, lecz jej nie dowodzą.", "Wyniki dowodzą chyba zależność.", "Zależność jest, bo wyniki mówią.", "Wyniki są zależnością samą."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Nie sądzę, żeby to ___ możliwe.", Options: []string{"było", "jest", "będzie", "być"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери правильный szyk formalny:", Options: []string{"W świetle dostępnych danych wniosek jest przedwczesny.", "W świetle dane dostępne wniosek przedwczesny jest.", "Dane świecą, więc wniosek wcześnie.", "Wniosek jest przed danymi."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит w odniesieniu do?", Options: []string{"w stosunku do / dotyczące", "po odniesieniu czegoś", "zamiast", "nagle"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери сложную poprawną konstrukcję:", Options: []string{"Nie dysponując pełnymi danymi, nie można sformułować ostatecznego wniosku.", "Nie dysponować dane, nie można wniosek.", "Bez dysponując pełnymi danymi, wniosek ostateczny nie.", "Dane nie dysponują, więc wniosek formułuje."}, CorrectIndex: 0, Points: 13},
	{Question: "Заполни пропуск: Gdyby nie wcześniejsze ustalenia, projekt ___ opóźniony.", Options: []string{"zostałby", "zostanie", "został", "zostać będzie"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери najbardziej naturalny wariant:", Options: []string{"Kwestia ta wymaga dalszej analizy.", "Ta kwestia chce więcej patrzenia.", "Kwestia potrzebuje robić analizę.", "Analiza wymaga kwestię."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит zważywszy na?", Options: []string{"biorąc pod uwagę", "ważąc coś fizycznie", "pomimo", "natychmiast po"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери wariant z właściwym rejestrem:", Options: []string{"Hipoteza ta wydaje się mało prawdopodobna.", "Ta hipoteza raczej chyba nie bardzo.", "Hipoteza robi się niemożliwa pewnie.", "To jest zła hipoteza i tyle."}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери zdanie z najlepszą niuansacją:", Options: []string{"Rozwiązanie jest obiecujące, aczkolwiek trudne do wdrożenia.", "Rozwiązanie dobre ale ciężkie i złe.", "Rozwiązanie obiecuje, lecz wdrożyć trudność.", "Rozwiązanie jest może fajne do robienia."}, CorrectIndex: 0, Points: 13},
}

var romanianLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: ___ carte este interesantă.", Options: []string{"Cartea", "Carte", "Cărți", "Unui carte"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Eu ___ românește.", Options: []string{"vorbesc", "vorbește", "vorbi", "vorbim"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный вариант: Noi ___ acasă.", Options: []string{"suntem", "este", "sunt eu", "fi"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Nu ___ cafea.", Options: []string{"beau", "bea", "băut", "bând"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: oraș - ___", Options: []string{"orașe", "orași", "orașuri", "orașelele"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Am douăzeci de ani.", "Sunt douăzeci de ani.", "Fac douăzeci ani mereu.", "Am douăzeci ani de vârstă sunt."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Ieri ___ la cinema.", Options: []string{"am fost", "sunt", "voi fi", "eram mâine"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный perfect compus:", Options: []string{"Am terminat tema.", "Eu terminat tema.", "Am termina tema.", "Terminam tema ieri terminat."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Mă gândesc ___ proiect.", Options: []string{"la", "de", "pe", "cu"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный comparativ:", Options: []string{"Textul acesta este mai clar decât celălalt.", "Textul acesta este mai clar ca celălalt decât.", "Textul este cel mai clar decât.", "Textul e mai bine clar."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Trebuie ___ mai devreme.", Options: []string{"să plec", "plec", "plecat", "să plecat"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Ne vedem peste o săptămână.", "Ne vedem prin o săptămână.", "Ne vedem pe săptămână trecută.", "Vedem noi săptămână peste."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Dacă aș avea timp, ___ mai mult.", Options: []string{"aș citi", "citesc", "voi citi ieri", "am citit mâine"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильный pronume:", Options: []string{"L-am văzut ieri.", "Am văzut îl ieri.", "I-am văzut ieri.", "Lui am văzut ieri."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Persoana ___ am vorbit locuiește aici.", Options: []string{"cu care", "care", "unde", "al cărui"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильный conjunctiv:", Options: []string{"Vreau să vină mai devreme.", "Vreau că vine mai devreme.", "Vreau să vine mai devreme.", "Vreau veni mai devreme."}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит totuși?", Options: []string{"cu toate acestea", "de aceea", "niciodată", "în loc de"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Depinde de situație.", "Depinde situația.", "Depinde la situație.", "Depinde cu situația."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильный pasiv:", Options: []string{"Documentul a fost semnat ieri.", "Documentul a semnat ieri.", "Documentul fost semna ieri.", "Documentul este semnat ieri trecut."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Deși ___ obosit, a continuat.", Options: []string{"era", "este mâine", "fi", "ar fi ieri mereu"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери правильный condițional perfect:", Options: []string{"Aș fi venit dacă aș fi putut.", "Aș veni dacă aș fi putut ieri.", "Aș fi veni dacă puteam.", "Veneam dacă aș putea ieri."}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит a lua în considerare?", Options: []string{"a ține cont de", "a lua fizic ceva", "a plăti imediat", "a uita"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери formalный вариант:", Options: []string{"Măsura s-a dovedit parțial eficientă.", "Măsura e un pic bună.", "Măsura face eficiență parțial.", "Măsura merge ceva."}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери правильный discurs indirect:", Options: []string{"A spus că va veni a doua zi.", "A spus că vine mâine ieri.", "A spus că ar veni mâine trecut.", "A spus venind a doua zi."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Nu cred că ___ dreptate.", Options: []string{"are", "să are", "va avea ieri", "a avea"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери construcția corectă:", Options: []string{"Analizând datele, am revizuit ipoteza.", "A analiza datele, am revizuit.", "Analizat datele, ipoteza revizuit.", "Datele analizându-se am revizuit."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит în pofida?", Options: []string{"în ciuda", "din cauza", "înainte de", "în loc de"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери точный академический вариант:", Options: []string{"Datele sugerează o legătură, dar nu o demonstrează.", "Datele dovedesc tot poate.", "Legătura este pentru că date.", "Datele sunt legătură completă."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Cu cât exersezi mai mult, ___ vorbești.", Options: []string{"cu atât mai bine", "cu atât mai bun", "mai mult bine", "atât cu bine"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит a pune sub semnul întrebării?", Options: []string{"a contesta", "a pune un semn grafic", "a aproba", "a întreba politicos"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери сложную корректную конструкцию:", Options: []string{"Dacă rezultatele ar fi fost disponibile, decizia s-ar fi schimbat.", "Dacă rezultatele erau disponibile mâine, decizia s-a schimbat.", "Dacă ar fi rezultatele disponibile, decizia schimbă.", "Rezultatele fiind disponibile, decizia ar schimba ieri."}, CorrectIndex: 0, Points: 13},
	{Question: "Заполни пропуск: În cazul în care se ___ noi date, concluzia va fi revizuită.", Options: []string{"confirmă", "confirmare", "confirmat", "vor confirma ieri"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери естественный formal register:", Options: []string{"Se impune o analiză suplimentară.", "Trebuie să mai uităm la asta.", "Analiza vrea mai mult făcut.", "E de făcut o analiză cumva."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит a lăsa de dorit?", Options: []string{"a fi nesatisfăcător", "a fi perfect", "a dori mult", "a abandona dorința"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери наиболее точный вариант:", Options: []string{"Concluzia pare prematură în lumina datelor disponibile.", "Concluzia e devreme pentru că datele luminează.", "Datele spun concluzie acum.", "Concluzia nu are timp."}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери предложение с лучшей нюансировкой:", Options: []string{"Soluția este promițătoare, deși dificil de implementat.", "Soluția e bună dar grea și rea.", "Soluția promite, implementarea dificultate.", "Soluția este poate frumoasă de făcut."}, CorrectIndex: 0, Points: 13},
}

var ukrainianLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: Це ___ книжка.", Options: []string{"цікава", "цікавий", "цікаве", "цікаві"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Я ___ українською.", Options: []string{"говорю", "говорить", "говорити", "говоримо"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный відмінок: Я бачу ___", Options: []string{"новий будинок", "нового будинок", "новим будинком", "новому будинок"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: У мене немає ___", Options: []string{"часу", "час", "часом", "часові"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: місто - ___", Options: []string{"міста", "місти", "містові", "містами є"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Мені двадцять років.", "Я двадцять років.", "У мене двадцять роки.", "Я маю двадцять років віком."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Учора я ___ вдома.", Options: []string{"був", "є", "буду", "бути"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильний доконаний вид:", Options: []string{"Я прочитав статтю.", "Я читав статтю і закінчив її завжди.", "Я прочитував статтю вчора повністю.", "Я читати статтю закінчив."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Я цікавлюся ___", Options: []string{"музикою", "музика", "музики", "музиці"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильний comparativ:", Options: []string{"Цей текст зрозуміліший за той.", "Цей текст більш зрозуміліший за той.", "Цей текст зрозумілий ніж той.", "Цей текст найзрозуміліший ніж."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Мені треба ___ раніше.", Options: []string{"вийти", "вийду", "вийшов", "виходжу що"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Побачимося за тиждень.", "Побачимося через тиждень тому.", "Побачимося на тиждень назад.", "Тиждень побачимося за."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Якби я мав час, ___ більше.", Options: []string{"читав би", "читаю", "буду читав учора", "прочитав завтра"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильне відносне речення:", Options: []string{"Це людина, яку я вчора зустрів.", "Це людина, що її я зустрів її.", "Це людина, який я зустрів.", "Це людина де зустрів."}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит однак?", Options: []string{"проте", "тому", "ніколи", "замість"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильний наказовий спосіб:", Options: []string{"Напишіть відповідь.", "Написати ви відповідь.", "Пишете відповідь наказ.", "Ви написали б відповідь зараз."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Він сказав, що ___ пізніше.", Options: []string{"прийде", "прийшов завтра", "прийти", "приходить учора"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Це залежить від обставин.", "Це залежить обставини.", "Це залежить на обставинах.", "Це залежить з обставинами."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильний passive:", Options: []string{"Документ було підписано вчора.", "Документ підписався вчора кимось.", "Документ був підписати вчора.", "Документ підписує вчора."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Хоча ___ пізно, ми продовжили роботу.", Options: []string{"було", "є завтра", "бути", "було б завтра"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит брати до уваги?", Options: []string{"враховувати", "брати фізично", "платити", "забувати"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери формальний варіант:", Options: []string{"Заходи виявилися частково ефективними.", "Заходи були трохи добрі.", "Заходи зробили ефективність частково.", "Заходи працюють щось."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Що більше практикуєш, ___ говориш.", Options: []string{"то краще", "то більш добре", "більше добре", "краще то"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери правильную складну конструкцію:", Options: []string{"Не маючи повних даних, не можна робити остаточний висновок.", "Не мати повні дані, висновок не можна.", "Без маючи даних, не можна висновок.", "Дані не мають, тому висновок робить."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Не думаю, що це ___ можливим.", Options: []string{"є", "бути", "буде вчора", "має бути було"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит ставити під сумнів?", Options: []string{"сумніватися / оскаржувати", "ставити під стіл", "підтверджувати", "питати ввічливо"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери точний академічний варіант:", Options: []string{"Дані вказують на зв'язок, але не доводять його.", "Дані доводять усе можливо.", "Зв'язок є бо дані.", "Дані самі є зв'язком."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери правильну умовну конструкцію:", Options: []string{"Якби результати були доступні раніше, рішення могло б змінитися.", "Якщо результати були б доступні вчора, рішення зміниться.", "Якби результати доступні, рішення змінити.", "Результати були доступні, рішення могло зміна."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит попри це?", Options: []string{"незважаючи на це", "через це", "перед цим", "замість цього"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"Питання потребує подальшого аналізу.", "Питання хоче ще дивитися.", "Аналіз треба робити питання.", "Питання є для аналізувати."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: У разі якщо ___ нові дані, висновок переглянуть.", Options: []string{"підтвердяться", "підтвердити", "підтверджено є", "підтвердять учора"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери корректну concessive construction:", Options: []string{"Хоч би якими переконливими здавалися аргументи, їх треба перевірити.", "Хоч аргументи здаються переконливі, треба перевірити.", "Хоч би аргументи є, перевірити треба їх.", "Аргументи хоч переконливо, перевірка треба."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит залишати бажати кращого?", Options: []string{"бути незадовільним", "бути ідеальним", "залишати побажання", "краще бажати"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери найбільш точний варіант:", Options: []string{"Висновок видається передчасним з огляду на наявні дані.", "Висновок ранній бо дані дивляться.", "Дані кажуть висновок зараз.", "Висновок не має часу."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит з огляду на?", Options: []string{"беручи до уваги", "дивлячись очима", "попри", "одразу після"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери речення з найкращою нюансировкою:", Options: []string{"Рішення перспективне, хоча його складно впровадити.", "Рішення добре але важке і погане.", "Рішення обіцяє, впровадження складність.", "Рішення може гарне робити."}, CorrectIndex: 0, Points: 13},
}

var kazakhLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: Мен қазақша ___", Options: []string{"сөйлеймін", "сөйлейді", "сөйлеу", "сөйлейсің"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Бұл ___ кітап.", Options: []string{"қызық", "қызықтымен", "қызыққа", "қызықтар"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный септік: Мен ___ көрдім.", Options: []string{"досымды", "досым", "досыммен", "досыма"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Менде уақыт ___", Options: []string{"бар", "бол", "еді", "жоқты"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: бала - ___", Options: []string{"балалар", "баладар", "балаларымға ғана", "балаларменді"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Мен жиырма жастамын.", "Мен жиырма жас бар.", "Мен жиырма жаспын әрқашан.", "Маған жиырма жыл бар."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Кеше мен үйде ___", Options: []string{"болдым", "боламын", "болу", "болып жатырмын ертең"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный барыс септік:", Options: []string{"Мен университетке барамын.", "Мен университетті барамын.", "Мен университетпен барамын.", "Мен университетде барамын."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Ол музыка___ қызығады.", Options: []string{"ға", "ны", "мен", "дан"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный салыстырмалы шырай:", Options: []string{"Бұл мәтін ана мәтіннен түсініктірек.", "Бұл мәтін ана мәтіннен ең түсініктілеу.", "Бұл мәтін түсінікті көп анадан.", "Бұл мәтін түсініктірек қарағанда ана."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Маған ертерек ___ керек.", Options: []string{"шығу", "шықтым", "шығамын", "шығып еді"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Бір аптадан кейін кездесеміз.", "Бір апта үшін кездестік ертең.", "Бір аптада бұрын кездесеміз.", "Кездесеміз аптадан бір."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Егер уақытым болса, көбірек ___", Options: []string{"оқыр едім", "оқимын кеше", "оқыдым ертең", "оқу керекпін"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери дұрыс тәуелдік форма:", Options: []string{"менің кітабым", "менің кітап", "мен кітапымдар", "менімен кітап"}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит дегенмен?", Options: []string{"алайда", "сондықтан", "ешқашан", "орнына"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильную относительную конструкцию:", Options: []string{"Кеше көрген адамым осында тұрады.", "Кеше адам көрдім тұрады.", "Адам кеше көрдім ол осында.", "Көрген кеше адамым тұрады осындамен."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Ол кейінірек келетінін ___", Options: []string{"айтты", "айтады ертең кеше", "айту", "айтқан болар келді"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Бұл жағдайға байланысты.", "Бұл жағдайды байланысты.", "Бұл жағдаймен байланыстырады маған.", "Бұл байланысты жағдайғады."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери дұрыс шартты рай:", Options: []string{"Нәтижелер ертерек белгілі болса, шешім өзгерер еді.", "Нәтижелер белгілі болса кеше, шешім өзгереді еді.", "Егер нәтижелер белгілі, шешім өзгеру.", "Нәтижелердің белгілісінде шешім өзгерді ертең."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Шаршағанына қарамастан, ол жұмысын ___", Options: []string{"жалғастырды", "жалғастыру ертең", "жалғастырады кеше", "жалғастырмақ еді болды"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит назарға алу?", Options: []string{"ескеру", "көзбен алу", "төлеу", "ұмыту"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери формальный вариант:", Options: []string{"Бұл шара ішінара тиімді болды.", "Бұл шара аздап жақсы болды.", "Шара тиімділік жасады.", "Шара бірдеңе істейді жақсы."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Неғұрлым көп жаттықсаң, ___ сөйлейсің.", Options: []string{"соғұрлым жақсы", "соғұрлым көбірек жақсы", "жақсырақ көп", "көп сонша жақсы"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери дұрыс көсемше құрылымы:", Options: []string{"Деректерді талдап, болжамды өзгерттік.", "Деректерді талдау, болжам өзгерттік.", "Талдаған деректер, өзгерттік болжамды.", "Деректер талдап болып болжам."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Бұл тұжырымның дұрыс екеніне күмән ___", Options: []string{"бар", "болу кеше", "еді емес", "жасайды"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит күмән келтіру?", Options: []string{"сенімсіз ету / даулау", "сұрақ қою ғана", "мақұлдау", "кейінге қалдыру"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери академиялық дәл вариант:", Options: []string{"Деректер байланыс бар екенін көрсетеді, бірақ дәлелдемейді.", "Деректер бәрін дәлелдейді мүмкін.", "Байланыс дерек болғандықтан бар.", "Деректер өздері байланыс."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери дұрыс есімше:", Options: []string{"Қарастырылып отырған мәселе маңызды.", "Қарастырып отырған мәселе маңыздысы.", "Қарастырылу мәселе маңызды.", "Мәселе қарастырып маңызды болады."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит соған қарамастан?", Options: []string{"бұған қарамастан", "сол себепті", "бұған дейін", "орнына"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"Бұл мәселе қосымша талдауды қажет етеді.", "Бұл мәселе тағы қарауды қалайды.", "Талдау мәселені істеу керек.", "Мәселе талдау үшін бар."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Жаңа деректер расталса, қорытынды ___", Options: []string{"қайта қаралады", "қайта қарау кеше", "қарады ертең", "қаралған болу"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери күрделі concessive construction:", Options: []string{"Уәждер қаншалықты сенімді көрінсе де, оларды тексеру қажет.", "Уәждер сенімді көрінсе, бірақ тексеру қажет еді.", "Қаншалықты уәждер бар, тексеру қажет.", "Уәждер көрініп сенімді тексеру керек."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит көңілден шықпау?", Options: []string{"күткен деңгейге жетпеу", "өте жақсы болу", "көңілді қалдыру физикалық", "ойын-сауық бастау"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери ең дәл вариант:", Options: []string{"Қолда бар деректерге сүйенсек, бұл қорытынды ерте сияқты.", "Деректер қарап тұр, қорытынды ерте.", "Қорытынды қазір дерек айтады.", "Қорытындының уақыты жоқ."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит тұрғысынан?", Options: []string{"көзқарасынан / жағынан", "тік тұрғаннан", "соған қарамастан", "дереу кейін"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери сөйлем с лучшей нюансировкой:", Options: []string{"Шешім үміт күттіреді, алайда оны іске асыру қиын.", "Шешім жақсы бірақ қиын және жаман.", "Шешім үміт береді іске асыру қиындығы.", "Шешім мүмкін жақсы істеу."}, CorrectIndex: 0, Points: 13},
}

var kyrgyzLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: Мен кыргызча ___", Options: []string{"сүйлөйм", "сүйлөйт", "сүйлөө", "сүйлөйсүң"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Бул ___ китеп.", Options: []string{"кызыктуу", "кызыктууга", "кызыктуулар", "кызыктуу менен"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный септик: Мен ___ көрдүм.", Options: []string{"досумду", "досум", "досум менен", "досума"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Менде убакыт ___", Options: []string{"бар", "бол", "эле", "жокту"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: бала - ___", Options: []string{"балдар", "балаларымга эле", "баладар", "баламен"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Мен жыйырма жаштамын.", "Мен жыйырма жаш бар.", "Мен жыйырма жылмын.", "Мага жыйырма жаш бар."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Кечээ мен үйдө ___", Options: []string{"болдум", "болом", "болуу", "болуп жатам эртең"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери туура багыт септик:", Options: []string{"Мен университетке барам.", "Мен университетти барам.", "Мен университет менен барам.", "Мен университетде барам."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Ал музыка___ кызыгат.", Options: []string{"га", "ны", "мен", "дан"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери салыштырма форма:", Options: []string{"Бул текст тигил тексттен түшүнүктүүрөөк.", "Бул текст эң түшүнүктүүрөөк тигилден.", "Бул текст түшүнүктүү көп.", "Бул тексттен тигил түшүнүктүү."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Мага эртерээк ___ керек.", Options: []string{"чыгуу", "чыктым", "чыгам", "чыгып эле"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Бир жумадан кийин жолугабыз.", "Бир жума үчүн жолугабыз кечээ.", "Бир жума мурун жолугабыз.", "Жолугабыз жума бирден."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Эгер убактым болсо, көбүрөөк ___", Options: []string{"окумакмын", "окуйм кечээ", "окудум эртең", "окуу керекмин"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери туура таандык форма:", Options: []string{"менин китебим", "менин китеп", "мен китебимдер", "мен менен китеп"}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит ошентсе да?", Options: []string{"бирок / ага карабай", "ошондуктан", "эч качан", "ордуна"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери туура аныктоочтук конструкция:", Options: []string{"Кечээ көргөн адамым ушул жерде жашайт.", "Кечээ адам көрдүм жашайт.", "Адам кечээ көрдүм ал жашайт.", "Көргөн кечээ адамым жашайт менен."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Ал кийин келерин ___", Options: []string{"айтты", "айтат кечээ эртең", "айтуу", "айткан келди"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Бул жагдайга байланыштуу.", "Бул жагдайды байланыштуу.", "Бул жагдай менен байланышат мага.", "Бул байланыштуу жагдайгады."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери туура шарттуу конструкция:", Options: []string{"Жыйынтыктар эртерээк белгилүү болсо, чечим өзгөрмөк.", "Жыйынтыктар белгилүү болсо кечээ, чечим өзгөрөт эле.", "Эгер жыйынтык белгилүү, чечим өзгөрүү.", "Белгилүү жыйынтыктарда чечим өзгөрдү эртең."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Чарчаганына карабай, ал ишин ___", Options: []string{"улантты", "улантуу эртең", "улантат кечээ", "улантмак болду эле"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит эске алуу?", Options: []string{"назарга алуу", "колго алуу", "төлөө", "унутуу"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери формальный вариант:", Options: []string{"Бул чара жарым-жартылай натыйжалуу болду.", "Бул чара аз жакшы болду.", "Чара натыйжалуулук кылды.", "Чара бир нерсе иштейт."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Канчалык көп машыксаң, ___ сүйлөйсүң.", Options: []string{"ошончолук жакшы", "ошончолук көбүрөөк жакшы", "жакшы көп", "көп ошончо жакшы"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери туура чакчыл конструкция:", Options: []string{"Маалыматтарды талдап, божомолду өзгөрттүк.", "Маалыматтарды талдоо, божомол өзгөрттүк.", "Талдаган маалыматтар, өзгөрттүк.", "Маалымат талдап болду божомол."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Бул тыянактын туура экенине күмөн ___", Options: []string{"бар", "болуу кечээ", "эле эмес", "жасайт"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит күмөн саноо?", Options: []string{"ишенбөө / шектенүү", "суроо берүү гана", "макул болуу", "кийинкиге калтыруу"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери академиялык так вариант:", Options: []string{"Маалыматтар байланыш бар экенин көрсөтөт, бирок далилдебейт.", "Маалыматтар баарын далилдейт мүмкүн.", "Байланыш маалымат болгондуктан бар.", "Маалыматтар өзү байланыш."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери туура атоочтук:", Options: []string{"Каралып жаткан маселе маанилүү.", "Карап жаткан маселе маанилүүсү.", "Каралуу маселе маанилүү.", "Маселе карап маанилүү болот."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит ага карабастан?", Options: []string{"ошого карабай", "ошондуктан", "буга чейин", "ордуна"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"Бул маселе кошумча талдоону талап кылат.", "Бул маселе дагы кароону каалайт.", "Талдоо маселени кылуу керек.", "Маселе талдоо үчүн бар."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Жаңы маалыматтар ырасталса, тыянак ___", Options: []string{"кайра каралат", "кайра кароо кечээ", "карады эртең", "каралган болуу"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери күрделі concessive construction:", Options: []string{"Далилдер канчалык ишенимдүү көрүнсө да, аларды текшерүү керек.", "Далилдер ишенимдүү көрүнөт, бирок текшерүү керек эле.", "Канчалык далилдер бар, текшерүү керек.", "Далилдер көрүнүп ишенимдүү текшерүү керек."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит күтүлгөн деңгээлге жетпөө?", Options: []string{"жетишсиз болуу", "абдан жакшы болуу", "деңгээлди күтүп туруу", "оюн баштоо"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери эң так вариант:", Options: []string{"Колдо бар маалыматтарга таянсак, бул тыянак эртелик кылат.", "Маалыматтар карап турат, тыянак эрте.", "Тыянак азыр маалымат айтат.", "Тыянактын убактысы жок."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит жагынан?", Options: []string{"көз карашынан / тараптан", "тик турганынан", "ошого карабай", "дароо кийин"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери сөйлем с лучшей нюансировкой:", Options: []string{"Чечим үмүт жаратат, бирок аны ишке ашыруу кыйын.", "Чечим жакшы бирок кыйын жана жаман.", "Чечим үмүт берет ишке ашыруу кыйындык.", "Чечим мүмкүн жакшы кылуу."}, CorrectIndex: 0, Points: 13},
}

var uzbekLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: Men o‘zbekcha ___", Options: []string{"gapiraman", "gapiradi", "gapirish", "gapirasan"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Bu ___ kitob.", Options: []string{"qiziqarli", "qiziqarliga", "qiziqarlilar", "qiziqarli bilan"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный kelishik: Men ___ ko‘rdim.", Options: []string{"do‘stimni", "do‘stim", "do‘stim bilan", "do‘stimga"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Menda vaqt ___", Options: []string{"bor", "bo‘l", "edi", "yo‘qni"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: bola - ___", Options: []string{"bolalar", "boladar", "bolalarga men", "bola bilanlar"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Men yigirma yoshdaman.", "Men yigirma yosh bor.", "Menda yigirma yoshman.", "Men yigirma yil bor."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Kecha men uyda ___", Options: []string{"edim", "bo‘laman", "bo‘lish", "bo‘lyapman ertaga"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный jo‘nalish kelishigi:", Options: []string{"Men universitetga boraman.", "Men universitetni boraman.", "Men universitet bilan boraman.", "Men universitetda boraman."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: U musiqa___ qiziqadi.", Options: []string{"ga", "ni", "bilan", "dan"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери comparative:", Options: []string{"Bu matn u matndan tushunarliroq.", "Bu matn eng tushunarliroq u matndan.", "Bu matn tushunarli ko‘p.", "Bu matndan u tushunarli."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Menga ertaroq ___ kerak.", Options: []string{"chiqish", "chiqdim", "chiqaman", "chiqib edi"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Bir haftadan keyin uchrashamiz.", "Bir hafta uchun uchrashamiz kecha.", "Bir hafta oldin uchrashamiz.", "Uchrashamiz hafta birdan."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Agar vaqtim bo‘lsa, ko‘proq ___", Options: []string{"o‘qirdim", "o‘qiyman kecha", "o‘qidim ertaga", "o‘qish kerakman"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильную possessive form:", Options: []string{"mening kitobim", "mening kitob", "men kitobimlar", "men bilan kitob"}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит shunga qaramay?", Options: []string{"baribir / biroq", "shuning uchun", "hech qachon", "o‘rniga"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери относительную конструкцию:", Options: []string{"Kecha ko‘rgan odamim shu yerda yashaydi.", "Kecha odam ko‘rdim yashaydi.", "Odam kecha ko‘rdim u yashaydi.", "Ko‘rgan kecha odamim yashaydi bilan."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: U keyinroq kelishini ___", Options: []string{"aytdi", "aytadi kecha ertaga", "aytish", "aytgan keldi"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Bu vaziyatga bog‘liq.", "Bu vaziyatni bog‘liq.", "Bu vaziyat bilan bog‘laydi menga.", "Bu bog‘liq vaziyatgadi."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери правильный conditional:", Options: []string{"Natijalar ertaroq ma'lum bo‘lsa, qaror o‘zgarardi.", "Natijalar ma'lum bo‘lsa kecha, qaror o‘zgaradi edi.", "Agar natija ma'lum, qaror o‘zgarish.", "Ma'lum natijalarda qaror o‘zgardi ertaga."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Charchaganiga qaramay, u ishini ___", Options: []string{"davom ettirdi", "davom ettirish ertaga", "davom ettiradi kecha", "davom ettirmoq edi bo‘ldi"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит hisobga olish?", Options: []string{"e'tiborga olish", "qo‘lga olish", "to‘lash", "unutish"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери formal variant:", Options: []string{"Bu chora qisman samarali bo‘ldi.", "Bu chora ozgina yaxshi bo‘ldi.", "Chora samaradorlik qildi.", "Chora nimadir ishlaydi."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Qancha ko‘p mashq qilsang, ___ gapirasan.", Options: []string{"shuncha yaxshi", "shuncha ko‘proq yaxshi", "yaxshi ko‘p", "ko‘p shuncha yaxshi"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери ravishdosh construction:", Options: []string{"Ma'lumotlarni tahlil qilib, taxminni o‘zgartirdik.", "Ma'lumotlarni tahlil qilish, taxmin o‘zgartirdik.", "Tahlil qilgan ma'lumotlar, o‘zgartirdik.", "Ma'lumot tahlil qilib bo‘ldi taxmin."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Bu xulosaning to‘g‘riligiga shubha ___", Options: []string{"bor", "bo‘lish kecha", "edi emas", "qiladi"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит shubha ostiga qo‘yish?", Options: []string{"savol ostiga olish / bahslashish", "faqat savol berish", "tasdiqlash", "kechiktirish"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери akademik aniq variant:", Options: []string{"Ma'lumotlar bog‘liqlik borligini ko‘rsatadi, ammo isbotlamaydi.", "Ma'lumotlar hammasini isbotlaydi balki.", "Bog‘liqlik ma'lumot bo‘lgani uchun bor.", "Ma'lumotlar o‘zi bog‘liqlik."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери sifatdosh:", Options: []string{"Ko‘rib chiqilayotgan masala muhim.", "Ko‘rib chiqqan masala muhimligi.", "Ko‘rib chiqish masala muhim.", "Masala ko‘rib muhim bo‘ladi."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит bunga qaramasdan?", Options: []string{"shunga qaramay", "shu sababli", "bundan oldin", "o‘rniga"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"Bu masala qo‘shimcha tahlilni talab qiladi.", "Bu masala yana qarashni xohlaydi.", "Tahlil masalani qilish kerak.", "Masala tahlil uchun bor."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Yangi ma'lumotlar tasdiqlansa, xulosa ___", Options: []string{"qayta ko‘rib chiqiladi", "qayta ko‘rish kecha", "ko‘rdi ertaga", "ko‘rilgan bo‘lish"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери complex concessive construction:", Options: []string{"Dalillar qanchalik ishonchli ko‘rinsa ham, ularni tekshirish zarur.", "Dalillar ishonchli ko‘rinsa, lekin tekshirish kerak edi.", "Qanchalik dalillar bor, tekshirish zarur.", "Dalillar ko‘rinib ishonchli tekshirish kerak."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит kutilgan darajaga yetmaslik?", Options: []string{"yetarli bo‘lmaslik", "juda yaxshi bo‘lish", "darajani kutib turish", "o‘yin boshlash"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери eng aniq variant:", Options: []string{"Mavjud ma'lumotlarga tayanilsa, bu xulosa erta ko‘rinadi.", "Ma'lumotlar qarab turibdi, xulosa erta.", "Xulosa hozir ma'lumot aytadi.", "Xulosaning vaqti yo‘q."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит nuqtayi nazaridan?", Options: []string{"jihatidan / qarashiga ko‘ra", "tik turganidan", "shunga qaramay", "darhol keyin"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери sentence with best nuance:", Options: []string{"Yechim umidli, biroq uni amalga oshirish qiyin.", "Yechim yaxshi lekin qiyin va yomon.", "Yechim umid beradi amalga oshirish qiyinlik.", "Yechim balki yaxshi qilish."}, CorrectIndex: 0, Points: 13},
}

var tajikLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: Ман тоҷикӣ ___", Options: []string{"гап мезанам", "гап мезанад", "гап задан", "гап мезанӣ"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Ин китоб ___ аст.", Options: []string{"ҷолиб", "ҷолибро", "ҷолибон", "ҷолиб ба"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный объект: Ман ___ дидам.", Options: []string{"дӯстамро", "дӯстам", "бо дӯстам", "ба дӯстам"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Ман вақт ___", Options: []string{"дорам", "дорад", "доштан", "ҳастам вақт"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: кӯдак - ___", Options: []string{"кӯдакон", "кӯдакҳоямро танҳо", "кӯдакроҳо", "кӯдакба"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Ман бистсола ҳастам.", "Ман бист сол дорам синну.", "Ман бист сол ҳастам дорам.", "Ба ман бист сол астам."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Дирӯз ман дар хона ___", Options: []string{"будам", "мешавам", "будан", "ҳастам фардо"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный вариант:", Options: []string{"Ман ба донишгоҳ меравам.", "Ман донишгоҳро меравам.", "Ман бо донишгоҳ меравам.", "Ман дар донишгоҳ меравам."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Ӯ ___ мусиқӣ шавқ дорад.", Options: []string{"ба", "ро", "бо", "аз"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери comparative:", Options: []string{"Ин матн аз он матн фаҳмотар аст.", "Ин матн фаҳмотар аз он бештар аст.", "Ин матн хеле фаҳмо аз.", "Ин матнтарин аз он."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Ба ман барвақттар ___ лозим аст.", Options: []string{"баромадан", "баромадам", "мебароям", "баромада будам"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Пас аз як ҳафта вомехӯрем.", "Барои як ҳафта дирӯз вомехӯрем.", "Пеш аз як ҳафта фардо вомехӯрем.", "Вомехӯрем ҳафта як пас."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Агар вақтам бошад, бештар ___", Options: []string{"мехондам", "мехонам дирӯз", "хондам фардо", "хондан лозимам"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери possessive construction:", Options: []string{"китоби ман", "ман китоб", "китобамҳо", "бо ман китоб"}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит бо вуҷуди ин?", Options: []string{"аммо / ҳарчанд", "бинобар ин", "ҳеҷ гоҳ", "ба ҷои"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери relative construction:", Options: []string{"Одаме, ки дирӯз дидам, дар ин ҷо зиндагӣ мекунад.", "Одам дирӯз дидам зиндагӣ мекунад.", "Одам ки ман дидам ӯ зиндагӣ.", "Дидам дирӯз одам зиндагӣ бо."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Ӯ гуфт, ки дертар ___", Options: []string{"меояд", "омад фардо", "омадан", "меомад дирӯз фардо"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Ин ба вазъият вобаста аст.", "Ин вазъиятро вобаста аст.", "Ин бо вазъият вобаста мекунад.", "Ин вобаста ба вазъиятро."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери conditional:", Options: []string{"Агар натиҷаҳо пештар маълум мешуданд, қарор дигар мешуд.", "Агар натиҷаҳо маълум буданд фардо, қарор дигар мешавад.", "Натиҷаҳо маълум, қарор дигар.", "Маълум шудани натиҷаҳо қарор кард."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Бо вуҷуди хаста будан, ӯ корро ___", Options: []string{"давом дод", "давом додан фардо", "давом медиҳад дирӯз", "давом карда бошад буд"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит ба назар гирифтан?", Options: []string{"ба ҳисоб гирифтан", "бо чашм гирифтан", "пардохтан", "фаромӯш кардан"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери formal variant:", Options: []string{"Ин тадбир қисман самарабахш буд.", "Ин тадбир каме хуб буд.", "Тадбир самарабахшӣ кард.", "Тадбир чизе кор мекунад."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Ҳар қадар бештар машқ кунӣ, ___ гап мезанӣ.", Options: []string{"ҳамон қадар беҳтар", "ҳамон қадар зиёд хуб", "беҳтар зиёд", "зиёд ҳамон хуб"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери participial construction:", Options: []string{"Маълумотро таҳлил карда, фарзияро тағйир додем.", "Маълумотро таҳлил кардан, фарзия тағйир додем.", "Таҳлилшуда маълумот, тағйир додем.", "Маълумот таҳлил карда шуд фарзия."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Ба дурустии ин хулоса шубҳа ___", Options: []string{"ҳаст", "будан дирӯз", "нест буд", "мекунад"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит зери шубҳа гузоштан?", Options: []string{"мавриди савол қарор додан", "танҳо савол додан", "тасдиқ кардан", "ба таъхир гузоштан"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери academic precise variant:", Options: []string{"Маълумот робитаро нишон медиҳад, аммо онро исбот намекунад.", "Маълумот ҳама чизро шояд исбот мекунад.", "Робита ҳаст чун маълумот.", "Маълумот худ робита аст."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери correct formal phrase:", Options: []string{"Масъалаи баррасишаванда муҳим аст.", "Масъала баррасӣ карда истода муҳим.", "Баррасӣ масъала муҳим мешавад.", "Масъала дида муҳим аст."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит сарфи назар аз ин?", Options: []string{"бо вуҷуди ин", "бинобар ин", "пеш аз ин", "ба ҷои ин"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"Ин масъала таҳлили иловагиро талаб мекунад.", "Ин масъала боз нигоҳ кардан мехоҳад.", "Таҳлил масъаларо кардан лозим.", "Масъала барои таҳлил ҳаст."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Агар маълумоти нав тасдиқ шавад, хулоса ___", Options: []string{"аз нав баррасӣ мешавад", "аз нав баррасӣ кардан дирӯз", "баррасӣ кард фардо", "баррасишуда бошад"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери complex concessive construction:", Options: []string{"Далелҳо ҳар қадар боварибахш намоянд ҳам, бояд санҷида шаванд.", "Далелҳо боварибахшанд, аммо бояд санҷиш буд.", "Ҳар қадар далел ҳаст, санҷидан лозим.", "Далелҳо намоён боварибахш санҷиш."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит ба интизориҳо ҷавобгӯ набудан?", Options: []string{"нокифоя будан", "комилан хуб будан", "интизор шудан", "бозӣ оғоз кардан"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери most precise variant:", Options: []string{"Бо такя ба маълумоти мавҷуда, ин хулоса бармаҳал менамояд.", "Маълумот нигоҳ мекунад, хулоса барвақт.", "Хулоса ҳоло маълумот мегӯяд.", "Хулоса вақт надорад."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит аз нуқтаи назар?", Options: []string{"аз ҷиҳат / аз дидгоҳ", "аз ҷои истодан", "бо вуҷуди", "дарҳол баъд"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери sentence with best nuance:", Options: []string{"Роҳҳал умедбахш аст, ҳарчанд татбиқи он душвор мебошад.", "Роҳҳал хуб аст аммо душвор ва бад.", "Роҳҳал умед медиҳад татбиқ душворӣ.", "Роҳҳал шояд хуб кардан."}, CorrectIndex: 0, Points: 13},
}

var tatarLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: Мин татарча ___", Options: []string{"сөйләшәм", "сөйләшә", "сөйләшү", "сөйләшәсең"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Бу ___ китап.", Options: []string{"кызыклы", "кызыклыга", "кызыклар", "кызыклы белән"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный килеш: Мин ___ күрдем.", Options: []string{"дустымны", "дустым", "дустым белән", "дустыма"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Минем вакытым ___", Options: []string{"бар", "бул", "иде", "юклы"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: бала - ___", Options: []string{"балалар", "баладар", "балаларымга гына", "бала беләннәр"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Миңа егерме яшь.", "Мин егерме яшь бар.", "Мин егерме яшьмен һәрчак.", "Миңа егерме ел бар."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Кичә мин өйдә ___", Options: []string{"булдым", "булам", "булу", "булып торам иртәгә"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери юнәлеш килеше:", Options: []string{"Мин университетка барам.", "Мин университетны барам.", "Мин университет белән барам.", "Мин университетта барам."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Ул музыка___ кызыксына.", Options: []string{"га", "ны", "белән", "дан"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери comparative:", Options: []string{"Бу текст теге тексттан аңлаешлырак.", "Бу текст иң аңлаешлырак тегеннән.", "Бу текст аңлаешлы күп.", "Бу тексттан теге аңлаешлы."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Миңа иртәрәк ___ кирәк.", Options: []string{"чыгу", "чыктым", "чыгам", "чыгып иде"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Бер атнадан соң очрашабыз.", "Бер атна өчен очрашабыз кичә.", "Бер атна элек очрашабыз.", "Очрашабыз атна бердән."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Әгәр вакытым булса, күбрәк ___", Options: []string{"укыр идем", "укыйм кичә", "укыдым иртәгә", "уку кирәкмен"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери possessive form:", Options: []string{"минем китабым", "минем китап", "мин китабымнар", "мин белән китап"}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит шулай да?", Options: []string{"шуңа карамастан", "шуңа күрә", "беркайчан", "урынына"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери relative construction:", Options: []string{"Кичә күргән кешем монда яши.", "Кичә кеше күрдем яши.", "Кеше кичә күрдем ул яши.", "Күргән кичә кешем яши белән."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Ул соңрак киләчәген ___", Options: []string{"әйтте", "әйтә кичә иртәгә", "әйтү", "әйткән килде"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Бу хәлгә бәйле.", "Бу хәлне бәйле.", "Бу хәл белән бәйли миңа.", "Бу бәйле хәлгәде."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери conditional:", Options: []string{"Нәтиҗәләр иртәрәк билгеле булса, карар үзгәрер иде.", "Нәтиҗәләр билгеле булса кичә, карар үзгәрә иде.", "Әгәр нәтиҗә билгеле, карар үзгәрү.", "Билгеле нәтиҗәләрдә карар үзгәрде иртәгә."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Арыган булуына карамастан, ул эшен ___", Options: []string{"дәвам итте", "дәвам итү иртәгә", "дәвам итә кичә", "дәвам итмәк булды иде"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит исәпкә алу?", Options: []string{"игътибарга алу", "кулга алу", "түләү", "оныту"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери formal variant:", Options: []string{"Бу чара өлешчә нәтиҗәле булды.", "Бу чара әзрәк яхшы булды.", "Чара нәтиҗәлелек ясады.", "Чара нәрсәдер эшли."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Күпме күбрәк күнексәң, ___ сөйләшәсең.", Options: []string{"шулкадәр яхшырак", "шулкадәр күбрәк яхшы", "яхшы күп", "күп шулкадәр яхшы"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери хәл фигыль construction:", Options: []string{"Мәгълүматны анализлап, фаразны үзгәрттек.", "Мәгълүматны анализлау, фараз үзгәрттек.", "Анализланган мәгълүмат, үзгәрттек.", "Мәгълүмат анализлап булды фараз."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Бу нәтиҗәнең дөреслегенә шик ___", Options: []string{"бар", "булу кичә", "иде түгел", "ясый"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит шик астына кую?", Options: []string{"сорау астына алу / бәхәсләшү", "сорау гына бирү", "раслау", "кичектерү"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери academic precise variant:", Options: []string{"Мәгълүмат бәйләнеш барлыгын күрсәтә, әмма аны исбатламый.", "Мәгълүмат барысын бәлки исбатлый.", "Бәйләнеш мәгълүмат булганга бар.", "Мәгълүмат үзе бәйләнеш."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери сыйфат фигыль:", Options: []string{"Карала торган мәсьәлә мөһим.", "Карап торган мәсьәлә мөһимлеге.", "Каралу мәсьәлә мөһим.", "Мәсьәлә карап мөһим була."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит моңа карамастан?", Options: []string{"шуңа да карамастан", "шуңа күрә", "моңа кадәр", "урынына"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"Бу мәсьәлә өстәмә анализ таләп итә.", "Бу мәсьәлә тагын карарга тели.", "Анализ мәсьәләне эшләргә кирәк.", "Мәсьәлә анализ өчен бар."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Яңа мәгълүмат расланса, нәтиҗә ___", Options: []string{"яңадан каралачак", "яңадан карау кичә", "карады иртәгә", "каралган булу"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери complex concessive construction:", Options: []string{"Дәлилләр никадәр ышандырырлык күренсә дә, аларны тикшерергә кирәк.", "Дәлилләр ышандырырлык күренә, ләкин тикшерү кирәк иде.", "Никадәр дәлил бар, тикшерү кирәк.", "Дәлилләр күренеп ышанычлы тикшерү кирәк."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит көтелгән дәрәҗәгә җитмәү?", Options: []string{"җитәрлек булмау", "бик яхшы булу", "дәрәҗә көтеп тору", "уен башлау"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери most precise variant:", Options: []string{"Булган мәгълүматка таянсак, бу нәтиҗә иртәрәк кебек.", "Мәгълүмат карап тора, нәтиҗә иртә.", "Нәтиҗә хәзер мәгълүмат әйтә.", "Нәтиҗәнең вакыты юк."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит күзлегеннән?", Options: []string{"карашыннан / ягыннан", "басып торудан", "шуңа карамастан", "шунда ук соң"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери sentence with best nuance:", Options: []string{"Чишелеш өметле, әмма аны гамәлгә ашыру кыен.", "Чишелеш яхшы ләкин кыен һәм начар.", "Чишелеш өмет бирә гамәлгә ашыру авырлык.", "Чишелеш бәлки яхшы эшләү."}, CorrectIndex: 0, Points: 13},
}

var armenianLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: Ես հայերեն ___", Options: []string{"խոսում եմ", "խոսում է", "խոսել", "խոսում ես"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Սա ___ գիրք է։", Options: []string{"հետաքրքիր", "հետաքրքիրով", "հետաքրքիրներ", "հետաքրքիրին"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный вариант: Նա Երևանում ___", Options: []string{"ապրում է", "ապրում եմ", "ապրել", "ապրում ես"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Ես ջուր ___", Options: []string{"խմում եմ", "խմում է", "խմել", "խմում ես"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: ուսանող - ___", Options: []string{"ուսանողներ", "ուսանողով", "ուսանողիներ", "ուսանողի"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"Ես քսան տարեկան եմ։", "Ես քսան տարի ունեմ։", "Ես քսան տարիք եմ։", "Ինձ քսան տարի է միշտ։"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: Երեկ ես տուն ___", Options: []string{"գնացի", "գնում եմ", "գնալ", "կգնամ երեկ"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный вариант:", Options: []string{"Ես համալսարան եմ գնում։", "Ես համալսարանը եմ գնում։", "Ես համալսարանով եմ գնում։", "Ես համալսարանի մեջ գնում եմ։"}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Նա պատմությամբ ___", Options: []string{"հետաքրքրվում է", "հետաքրքրվում եմ", "հետաքրքրվել", "հետաքրքիր է պատմություն"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери comparative:", Options: []string{"Այս տեքստն ավելի պարզ է, քան այն։", "Այս տեքստը պարզ ավելի այնից։", "Այս տեքստը ամենապարզ քան այն։", "Այս տեքստը շատ պարզից է։"}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Վաղը պետք է շուտ ___", Options: []string{"գնամ", "գնացի", "գնալ եմ", "գնացել երեկ"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"Մեկ շաբաթից կհանդիպենք։", "Մեկ շաբաթի համար երեկ կհանդիպենք։", "Մեկ շաբաթ առաջ վաղը կհանդիպենք։", "Կհանդիպենք շաբաթ մեկից։"}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: Եթե ժամանակ ունենամ, ավելի շատ ___", Options: []string{"կկարդամ", "կարդացի երեկ", "կարդում էի վաղը", "կարդալ պետք եմ"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери possessive construction:", Options: []string{"իմ գիրքը", "ես գիրք", "գիրքսներ", "ինձ հետ գիրք"}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит այնուամենայնիվ?", Options: []string{"չնայած դրան", "դրա պատճառով", "երբեք", "փոխարենը"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери relative construction:", Options: []string{"Մարդը, ում երեկ տեսա, այստեղ է ապրում։", "Մարդը երեկ տեսա ապրում է այստեղ։", "Մարդ որ ես տեսա նա ապրում։", "Տեսա երեկ մարդը ապրում հետ։"}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: Նա ասաց, որ ուշ ___", Options: []string{"կգա", "եկավ վաղը", "գալ", "գալիս էր երեկ վաղը"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"Դա կախված է իրավիճակից։", "Դա իրավիճակը կախված է։", "Դա իրավիճակով կախում է։", "Դա կախված իրավիճակը է։"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери conditional:", Options: []string{"Եթե իմանայի, ավելի շուտ կասեի։", "Եթե գիտեի վաղը, կասեմ երեկ։", "Եթե իմանալ, ասել շուտ։", "Գիտեի եթե, ասացի վաղը։"}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Չնայած հոգնած էր, նա աշխատանքը ___", Options: []string{"շարունակեց", "շարունակել վաղը", "շարունակում է երեկ", "շարունակած կլինի երեկ"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит հաշվի առնել?", Options: []string{"նկատի ունենալ", "հաշիվ վերցնել ձեռքով", "վճարել", "մոռանալ"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери formal variant:", Options: []string{"Այս միջոցառումը մասամբ արդյունավետ էր։", "Այս միջոցառումը մի քիչ լավ էր։", "Միջոցառումը արդյունավետություն արեց։", "Միջոցառումը ինչ-որ բան աշխատում է։"}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Որքան շատ պարապես, ___ կխոսես։", Options: []string{"այնքան ավելի լավ", "այնքան շատ լավ", "լավ շատ", "շատ այնքան լավ"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери participial construction:", Options: []string{"Վերլուծելով տվյալները՝ փոխեցինք վարկածը։", "Վերլուծել տվյալները՝ վարկածը փոխեցինք։", "Վերլուծված տվյալներ՝ փոխեցինք։", "Տվյալները վերլուծեցինք է վարկածը։"}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: Այս եզրակացության ճշտությունը կասկած ___", Options: []string{"է առաջացնում", "առաջացնել երեկ", "չէր առաջացնում վաղը", "անում է կասկածով"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит կասկածի տակ դնել?", Options: []string{"հարցականի տակ դնել", "միայն հարց տալ", "հաստատել", "հետաձգել"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери academic precise variant:", Options: []string{"Տվյալները կապ են ցույց տալիս, սակայն դա չեն ապացուցում։", "Տվյալները ամեն ինչ գուցե ապացուցում են։", "Կապ կա, որովհետև տվյալներ կան։", "Տվյալներն իրենք կապն են։"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери correct formal phrase:", Options: []string{"Քննարկվող հարցը կարևոր է։", "Քննարկում հարցը կարևորություն է։", "Հարցը քննարկել կարևոր է լինում։", "Հարցը նայելով կարևոր է։"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит չնայած դրան?", Options: []string{"այնուամենայնիվ", "դրա պատճառով", "մինչ այդ", "դրա փոխարեն"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"Այս հարցը լրացուցիչ վերլուծություն է պահանջում։", "Այս հարցը ուզում է նորից նայել։", "Վերլուծություն հարցը անել պետք է։", "Հարցը վերլուծության համար կա։"}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: Եթե նոր տվյալները հաստատվեն, եզրակացությունը ___", Options: []string{"կվերանայվի", "վերանայել երեկ", "վերանայեց վաղը", "վերանայված լինել"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери complex concessive construction:", Options: []string{"Որքան էլ փաստարկները համոզիչ թվան, դրանք պետք է ստուգվեն։", "Փաստարկները համոզիչ են, բայց ստուգում էր պետք։", "Որքան փաստարկ կա, ստուգել պետք է։", "Փաստարկները թվում համոզիչ ստուգում։"}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит ակնկալիքներին չհամապատասխանել?", Options: []string{"սպասված մակարդակին չհասնել", "լիովին գերազանց լինել", "սպասել լուռ", "խաղ սկսել"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери most precise variant:", Options: []string{"Առկա տվյալների հիման վրա այս եզրակացությունը վաղաժամ է թվում։", "Տվյալները նայում են, եզրակացությունը շուտ է։", "Եզրակացությունը հիմա տվյալներ է ասում։", "Եզրակացությունը ժամանակ չունի։"}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит տեսանկյունից?", Options: []string{"դիտանկյունից / առումով", "կանգնելու տեղից", "չնայած", "անմիջապես հետո"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери sentence with best nuance:", Options: []string{"Լուծումը խոստումնալից է, թեև դրա իրականացումը բարդ է։", "Լուծումը լավ է բայց բարդ և վատ։", "Լուծումը հույս է տալիս իրականացում դժվարություն։", "Լուծումը գուցե լավ անել։"}, CorrectIndex: 0, Points: 13},
}

var georgianLevelAssessmentQuestions = []levelQuestion{
	{Question: "Выбери правильный вариант: მე ქართულად ___", Options: []string{"ვლაპარაკობ", "ლაპარაკობს", "ლაპარაკი", "ლაპარაკობ"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: ეს ___ წიგნია.", Options: []string{"საინტერესო", "საინტერესოს", "საინტერესოები", "საინტერესოდან"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери правильный вариант: ის თბილისში ___", Options: []string{"ცხოვრობს", "ვცხოვრობ", "ცხოვრება", "ცხოვრობ"}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: მე წყალს ___", Options: []string{"ვსვამ", "სვამს", "სმა", "სვამ"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери plural: სტუდენტი - ___", Options: []string{"სტუდენტები", "სტუდენტებსი", "სტუდენტით", "სტუდენტის"}, CorrectIndex: 0, Points: 4},
	{Question: "Выбери естественный вариант:", Options: []string{"მე ოცი წლის ვარ.", "მე ოცი წელი მაქვს.", "მე ოცი ასაკი ვარ.", "ჩემთვის ოცი წელია ყოველთვის."}, CorrectIndex: 0, Points: 4},
	{Question: "Заполни пропуск: გუშინ სახლში ___", Options: []string{"ვიყავი", "ვარ", "ყოფნა", "ვიქნები გუშინ"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери правильный вариант:", Options: []string{"მე უნივერსიტეტში მივდივარ.", "მე უნივერსიტეტს მივდივარ.", "მე უნივერსიტეტით მივდივარ.", "მე უნივერსიტეტიდან ვარ მივდივარ."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: მას მუსიკა ___", Options: []string{"უყვარს", "მიყვარს", "სიყვარული", "უყვარხარ მუსიკა"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери comparative:", Options: []string{"ეს ტექსტი იმ ტექსტზე უფრო გასაგებია.", "ეს ტექსტი უფრო გასაგები იმზე.", "ეს ტექსტი ყველაზე გასაგებია ვიდრე ის.", "ეს ტექსტი გასაგებზე მეტია."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: ხვალ ადრე უნდა ___", Options: []string{"წავიდე", "წავედი", "წასვლა ვარ", "წავედი გუშინ"}, CorrectIndex: 0, Points: 5},
	{Question: "Выбери естественный вариант:", Options: []string{"ერთი კვირის შემდეგ შევხვდებით.", "ერთი კვირისთვის გუშინ შევხვდებით.", "ერთი კვირის წინ ხვალ შევხვდებით.", "შევხვდებით კვირა ერთიდან."}, CorrectIndex: 0, Points: 5},
	{Question: "Заполни пропуск: თუ დრო მექნება, მეტს ___", Options: []string{"წავიკითხავ", "წავიკითხე გუშინ", "ვკითხულობდი ხვალ", "წაკითხვა უნდა ვარ"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери possessive construction:", Options: []string{"ჩემი წიგნი", "მე წიგნი", "წიგნიჩემიები", "ჩემთან წიგნი"}, CorrectIndex: 0, Points: 7},
	{Question: "Что значит მიუხედავად ამისა?", Options: []string{"ამის მიუხედავად", "ამიტომ", "არასოდეს", "ამის ნაცვლად"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери relative construction:", Options: []string{"ადამიანი, რომელიც გუშინ ვნახე, აქ ცხოვრობს.", "ადამიანი გუშინ ვნახე ცხოვრობს აქ.", "ადამიანი რომელიც მე ვნახე ის ცხოვრობს.", "ვნახე გუშინ ადამიანი ცხოვრობსთან."}, CorrectIndex: 0, Points: 7},
	{Question: "Заполни пропуск: მან თქვა, რომ მოგვიანებით ___", Options: []string{"მოვიდოდა", "მოვიდა ხვალ", "მოსვლა", "მოდიოდა გუშინ ხვალ"}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери естественный вариант:", Options: []string{"ეს სიტუაციაზეა დამოკიდებული.", "ეს სიტუაციას დამოკიდებულია.", "ეს სიტუაციით დამოკიდებს.", "ეს დამოკიდებული სიტუაციასაა."}, CorrectIndex: 0, Points: 7},
	{Question: "Выбери conditional:", Options: []string{"რომ მცოდნოდა, უფრო ადრე გეტყოდი.", "თუ ვიცოდი ხვალ, ვეტყვი გუშინ.", "ცოდნა რომ, თქმა ადრე.", "ვიცოდი თუ, ვთქვი ხვალ."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: დაღლილობის მიუხედავად, მან მუშაობა ___", Options: []string{"გააგრძელა", "გაგრძელება ხვალ", "აგრძელებს გუშინ", "გაგრძელებული იქნება გუშინ"}, CorrectIndex: 0, Points: 9},
	{Question: "Что значит გათვალისწინება?", Options: []string{"მხედველობაში მიღება", "ხელში აღება", "გადახდა", "დავიწყება"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери formal variant:", Options: []string{"ეს ღონისძიება ნაწილობრივ ეფექტიანი იყო.", "ეს ღონისძიება ცოტა კარგი იყო.", "ღონისძიებამ ეფექტიანობა გააკეთა.", "ღონისძიება რაღაც მუშაობს."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: რაც უფრო მეტს ივარჯიშებ, ___ ილაპარაკებ.", Options: []string{"მით უკეთ", "მით მეტი კარგად", "კარგად ბევრი", "ბევრი მით კარგად"}, CorrectIndex: 0, Points: 9},
	{Question: "Выбери participial construction:", Options: []string{"მონაცემების გაანალიზების შემდეგ ჰიპოთეზა შევცვალეთ.", "მონაცემების გაანალიზება, ჰიპოთეზა შევცვალეთ.", "გაანალიზებული მონაცემები, შევცვალეთ.", "მონაცემები გაანალიზდა არის ჰიპოთეზა."}, CorrectIndex: 0, Points: 9},
	{Question: "Заполни пропуск: ამ დასკვნის სისწორე ეჭვს ___", Options: []string{"იწვევს", "გამოწვევა გუშინ", "არ იწვევდა ხვალ", "აკეთებს ეჭვით"}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит ეჭვქვეშ დაყენება?", Options: []string{"კითხვის ნიშნის ქვეშ დაყენება", "მხოლოდ კითხვის დასმა", "დადასტურება", "გადადება"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери academic precise variant:", Options: []string{"მონაცემები კავშირს აჩვენებს, მაგრამ მას არ ამტკიცებს.", "მონაცემები ყველაფერს ალბათ ამტკიცებს.", "კავშირი არის რადგან მონაცემებია.", "მონაცემები თვითონ კავშირია."}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери correct formal phrase:", Options: []string{"განსახილველი საკითხი მნიშვნელოვანია.", "განხილვა საკითხი მნიშვნელოვანია.", "საკითხი განხილვა მნიშვნელოვანია ხდება.", "საკითხი ნახვით მნიშვნელოვანია."}, CorrectIndex: 0, Points: 11},
	{Question: "Что значит ამის მიუხედავად?", Options: []string{"მიუხედავად ამისა", "ამის გამო", "მანამდე", "ამის ნაცვლად"}, CorrectIndex: 0, Points: 11},
	{Question: "Выбери natural formal register:", Options: []string{"ეს საკითხი დამატებით ანალიზს მოითხოვს.", "ეს საკითხი კიდევ ნახვას უნდა.", "ანალიზი საკითხი გაკეთება საჭიროა.", "საკითხი ანალიზისთვის არის."}, CorrectIndex: 0, Points: 11},
	{Question: "Заполни пропуск: თუ ახალი ინფორმაცია დადასტურდება, დასკვნა ___", Options: []string{"ხელახლა გადაიხედება", "გადახედვა გუშინ", "გადახედა ხვალ", "გადახედილი ყოფნა"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери complex concessive construction:", Options: []string{"რაც უნდა დამაჯერებლად ჩანდეს არგუმენტები, ისინი უნდა შემოწმდეს.", "არგუმენტები დამაჯერებელია, მაგრამ შემოწმება იყო საჭირო.", "რამდენი არგუმენტია, შემოწმება საჭიროა.", "არგუმენტები ჩანს დამაჯერებელი შემოწმება."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит მოლოდინებს ვერ აკმაყოფილებს?", Options: []string{"საკმარის დონეს ვერ აღწევს", "სრულად აღემატება", "ჩუმად ელოდება", "თამაშს იწყებს"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери most precise variant:", Options: []string{"არსებული მონაცემების საფუძველზე, ეს დასკვნა ნაადრევად ჩანს.", "მონაცემები უყურებს, დასკვნა ადრეა.", "დასკვნა ახლა მონაცემებს ამბობს.", "დასკვნას დრო არ აქვს."}, CorrectIndex: 0, Points: 13},
	{Question: "Что значит თვალსაზრისით?", Options: []string{"კუთხით / ხედვით", "დგომის ადგილიდან", "მიუხედავად", "მაშინვე შემდეგ"}, CorrectIndex: 0, Points: 13},
	{Question: "Выбери sentence with best nuance:", Options: []string{"გადაწყვეტა იმედისმომცემია, თუმცა მისი განხორციელება რთულია.", "გადაწყვეტა კარგია მაგრამ რთული და ცუდი.", "გადაწყვეტა იმედს აძლევს განხორციელება სირთულე.", "გადაწყვეტა ალბათ კარგი გაკეთება."}, CorrectIndex: 0, Points: 13},
}
